/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "CDR"
 * 	found in "../cdr.asn1"
 * 	`asn1c -fskeletons-copy -fnative-types`
 */

#ifndef	_APNSelectionMode_H_
#define	_APNSelectionMode_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum APNSelectionMode {
	APNSelectionMode_mSorNetworkProvidedSubscriptionVerified	= 0,
	APNSelectionMode_mSProvidedSubscriptionNotVerified	= 1,
	APNSelectionMode_networkProvidedSubscriptionNotVerified	= 2
} e_APNSelectionMode;

/* APNSelectionMode */
typedef long	 APNSelectionMode_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_APNSelectionMode;
asn_struct_free_f APNSelectionMode_free;
asn_struct_print_f APNSelectionMode_print;
asn_constr_check_f APNSelectionMode_constraint;
ber_type_decoder_f APNSelectionMode_decode_ber;
der_type_encoder_f APNSelectionMode_encode_der;
xer_type_decoder_f APNSelectionMode_decode_xer;
xer_type_encoder_f APNSelectionMode_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _APNSelectionMode_H_ */
#include <asn_internal.h>
