/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "CDR"
 * 	found in "../cdr.asn1"
 * 	`asn1c -fskeletons-copy -fnative-types`
 */

#ifndef	_CallingPartyCategory_H_
#define	_CallingPartyCategory_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Category.h"

#ifdef __cplusplus
extern "C" {
#endif

/* CallingPartyCategory */
typedef Category_t	 CallingPartyCategory_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CallingPartyCategory;
asn_struct_free_f CallingPartyCategory_free;
asn_struct_print_f CallingPartyCategory_print;
asn_constr_check_f CallingPartyCategory_constraint;
ber_type_decoder_f CallingPartyCategory_decode_ber;
der_type_encoder_f CallingPartyCategory_encode_der;
xer_type_decoder_f CallingPartyCategory_decode_xer;
xer_type_encoder_f CallingPartyCategory_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _CallingPartyCategory_H_ */
#include <asn_internal.h>
