/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "CDR"
 * 	found in "../cdr.asn1"
 * 	`asn1c -fskeletons-copy -fnative-types`
 */

#ifndef	_CallType_H_
#define	_CallType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CallType {
	CallType_mobileOriginated	= 0,
	CallType_mobileTerminated	= 1
} e_CallType;

/* CallType */
typedef long	 CallType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CallType;
asn_struct_free_f CallType_free;
asn_struct_print_f CallType_print;
asn_constr_check_f CallType_constraint;
ber_type_decoder_f CallType_decode_ber;
der_type_encoder_f CallType_encode_der;
xer_type_decoder_f CallType_decode_xer;
xer_type_encoder_f CallType_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _CallType_H_ */
#include <asn_internal.h>
