/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "CDR"
 * 	found in "../cdr.asn1"
 * 	`asn1c -fskeletons-copy -fnative-types`
 */

#ifndef	_CallEventRecord_H_
#define	_CallEventRecord_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SGSNPDPRecord.h"
#include "GGSNPDPRecord.h"
#include "SGSNMMRecord.h"
#include "SGSNSMORecord.h"
#include "SGSNSMTRecord.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CallEventRecord_PR {
	CallEventRecord_PR_NOTHING,	/* No components present */
	CallEventRecord_PR_sgsnPDPRecord,
	CallEventRecord_PR_ggsnPDPRecord,
	CallEventRecord_PR_sgsnMMRecord,
	CallEventRecord_PR_sgsnSMORecord,
	CallEventRecord_PR_sgsnSMTRecord
} CallEventRecord_PR;

/* CallEventRecord */
typedef struct CallEventRecord {
	CallEventRecord_PR present;
	union CallEventRecord_u {
		SGSNPDPRecord_t	 sgsnPDPRecord;
		GGSNPDPRecord_t	 ggsnPDPRecord;
		SGSNMMRecord_t	 sgsnMMRecord;
		SGSNSMORecord_t	 sgsnSMORecord;
		SGSNSMTRecord_t	 sgsnSMTRecord;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CallEventRecord_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CallEventRecord;

#ifdef __cplusplus
}
#endif

#endif	/* _CallEventRecord_H_ */
#include <asn_internal.h>
