/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "CDR"
 * 	found in "../cdr.asn1"
 * 	`asn1c -fskeletons-copy -fnative-types`
 */

#ifndef	_CallEventRecordType_H_
#define	_CallEventRecordType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CallEventRecordType {
	CallEventRecordType_moCallRecord	= 0,
	CallEventRecordType_mtCallRecord	= 1,
	CallEventRecordType_roamingRecord	= 2,
	CallEventRecordType_incGatewayRecord	= 3,
	CallEventRecordType_outGatewayRecord	= 4,
	CallEventRecordType_transitCallRecord	= 5,
	CallEventRecordType_moSMSRecord	= 6,
	CallEventRecordType_mtSMSRecord	= 7,
	CallEventRecordType_moSMSIWRecord	= 8,
	CallEventRecordType_mtSMSGWRecord	= 9,
	CallEventRecordType_ssActionRecord	= 10,
	CallEventRecordType_hlrIntRecord	= 11,
	CallEventRecordType_locUpdateHLRRecord	= 12,
	CallEventRecordType_locUpdateVLRRecord	= 13,
	CallEventRecordType_commonEquipRecord	= 14,
	CallEventRecordType_moTraceRecord	= 15,
	CallEventRecordType_mtTraceRecord	= 16,
	CallEventRecordType_termCAMELRecord	= 17,
	CallEventRecordType_sgsnPDPRecord	= 18,
	CallEventRecordType_ggsnPDPRecord	= 19,
	CallEventRecordType_sgsnMMRecord	= 20,
	CallEventRecordType_sgsnSMORecord	= 21,
	CallEventRecordType_sgsnSMTRecord	= 22
} e_CallEventRecordType;

/* CallEventRecordType */
typedef long	 CallEventRecordType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CallEventRecordType;
asn_struct_free_f CallEventRecordType_free;
asn_struct_print_f CallEventRecordType_print;
asn_constr_check_f CallEventRecordType_constraint;
ber_type_decoder_f CallEventRecordType_decode_ber;
der_type_encoder_f CallEventRecordType_encode_der;
xer_type_decoder_f CallEventRecordType_decode_xer;
xer_type_encoder_f CallEventRecordType_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _CallEventRecordType_H_ */
#include <asn_internal.h>
