/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "CDR"
 * 	found in "../cdr.asn1"
 * 	`asn1c -fskeletons-copy -fnative-types`
 */

#ifndef	_CallEventDataFile_H_
#define	_CallEventDataFile_H_


#include <asn_application.h>

/* Including external dependencies */
#include "HeaderRecord.h"
#include "TrailerRecord.h"
#include "ManagementExtensions.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct CallEventRecord;

/* CallEventDataFile */
typedef struct CallEventDataFile {
	HeaderRecord_t	 headerRecord;
	struct CallEventDataFile__callEventRecords {
		A_SEQUENCE_OF(struct CallEventRecord) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} callEventRecords;
	TrailerRecord_t	 trailerRecord;
	ManagementExtensions_t	 extensions;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CallEventDataFile_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CallEventDataFile;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "CallEventRecord.h"

#endif	/* _CallEventDataFile_H_ */
#include <asn_internal.h>
