/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "CDR"
 * 	found in "../cdr.asn1"
 * 	`asn1c -fskeletons-copy -fnative-types`
 */

#ifndef	_CAMELInitCFIndicator_H_
#define	_CAMELInitCFIndicator_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CAMELInitCFIndicator {
	CAMELInitCFIndicator_noCAMELCallForwarding	= 0,
	CAMELInitCFIndicator_cAMELCallForwarding	= 1
} e_CAMELInitCFIndicator;

/* CAMELInitCFIndicator */
typedef long	 CAMELInitCFIndicator_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CAMELInitCFIndicator;
asn_struct_free_f CAMELInitCFIndicator_free;
asn_struct_print_f CAMELInitCFIndicator_print;
asn_constr_check_f CAMELInitCFIndicator_constraint;
ber_type_decoder_f CAMELInitCFIndicator_decode_ber;
der_type_encoder_f CAMELInitCFIndicator_encode_der;
xer_type_decoder_f CAMELInitCFIndicator_decode_xer;
xer_type_encoder_f CAMELInitCFIndicator_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _CAMELInitCFIndicator_H_ */
#include <asn_internal.h>
