/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "CDR"
 * 	found in "../cdr.asn1"
 * 	`asn1c -fskeletons-copy -fnative-types`
 */

#ifndef	_CAMELInformationSMS_H_
#define	_CAMELInformationSMS_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SCFAddress.h"
#include "ServiceKey.h"
#include "DefaultSMS-Handling.h"
#include "CallingNumber.h"
#include "CalledNumber.h"
#include "AddressString.h"
#include "FreeFormatData.h"
#include "CallReferenceNumber.h"
#include <constr_SET.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */

/*
 * Method of determining the components presence
 */
typedef enum CAMELInformationSMS_PR {
	CAMELInformationSMS_PR_sCFAddress,	/* Member sCFAddress is present */
	CAMELInformationSMS_PR_serviceKey,	/* Member serviceKey is present */
	CAMELInformationSMS_PR_defaultSMSHandling,	/* Member defaultSMSHandling is present */
	CAMELInformationSMS_PR_cAMELCallingPartyNumber,	/* Member cAMELCallingPartyNumber is present */
	CAMELInformationSMS_PR_cAMELDestinationSubscriberNumber,	/* Member cAMELDestinationSubscriberNumber is present */
	CAMELInformationSMS_PR_cAMELSMSCAddress,	/* Member cAMELSMSCAddress is present */
	CAMELInformationSMS_PR_freeFormatData,	/* Member freeFormatData is present */
	CAMELInformationSMS_PR_sMSReferenceNumber,	/* Member sMSReferenceNumber is present */
} CAMELInformationSMS_PR;

/* CAMELInformationSMS */
typedef struct CAMELInformationSMS {
	SCFAddress_t	*sCFAddress	/* OPTIONAL */;
	ServiceKey_t	*serviceKey	/* OPTIONAL */;
	DefaultSMS_Handling_t	*defaultSMSHandling	/* OPTIONAL */;
	CallingNumber_t	*cAMELCallingPartyNumber	/* OPTIONAL */;
	CalledNumber_t	*cAMELDestinationSubscriberNumber	/* OPTIONAL */;
	AddressString_t	*cAMELSMSCAddress	/* OPTIONAL */;
	FreeFormatData_t	*freeFormatData	/* OPTIONAL */;
	CallReferenceNumber_t	*sMSReferenceNumber	/* OPTIONAL */;
	
	/* Presence bitmask: ASN_SET_ISPRESENT(pCAMELInformationSMS, CAMELInformationSMS_PR_x) */
	unsigned int _presence_map
		[((8+(8*sizeof(unsigned int))-1)/(8*sizeof(unsigned int)))];
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CAMELInformationSMS_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CAMELInformationSMS;

#ifdef __cplusplus
}
#endif

#endif	/* _CAMELInformationSMS_H_ */
#include <asn_internal.h>
