/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "CDR"
 * 	found in "../cdr.asn1"
 * 	`asn1c -fskeletons-copy -fnative-types`
 */

#ifndef	_CAMELInformationPDP_H_
#define	_CAMELInformationPDP_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SCFAddress.h"
#include "ServiceKey.h"
#include "DefaultGPRS-Handling.h"
#include "CAMELAccessPointNameNI.h"
#include "CAMELAccessPointNameOI.h"
#include "NumberOfDPEncountered.h"
#include "LevelOfCAMELService.h"
#include "FreeFormatData.h"
#include "FFDAppendIndicator.h"
#include <constr_SET.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */

/*
 * Method of determining the components presence
 */
typedef enum CAMELInformationPDP_PR {
	CAMELInformationPDP_PR_sCFAddress,	/* Member sCFAddress is present */
	CAMELInformationPDP_PR_serviceKey,	/* Member serviceKey is present */
	CAMELInformationPDP_PR_defaultTransactionHandling,	/* Member defaultTransactionHandling is present */
	CAMELInformationPDP_PR_cAMELAccessPointNameNI,	/* Member cAMELAccessPointNameNI is present */
	CAMELInformationPDP_PR_cAMELAccessPointNameOI,	/* Member cAMELAccessPointNameOI is present */
	CAMELInformationPDP_PR_numberOfDPEncountered,	/* Member numberOfDPEncountered is present */
	CAMELInformationPDP_PR_levelOfCAMELService,	/* Member levelOfCAMELService is present */
	CAMELInformationPDP_PR_freeFormatData,	/* Member freeFormatData is present */
	CAMELInformationPDP_PR_fFDAppendIndicator,	/* Member fFDAppendIndicator is present */
} CAMELInformationPDP_PR;

/* CAMELInformationPDP */
typedef struct CAMELInformationPDP {
	SCFAddress_t	*sCFAddress	/* OPTIONAL */;
	ServiceKey_t	*serviceKey	/* OPTIONAL */;
	DefaultGPRS_Handling_t	*defaultTransactionHandling	/* OPTIONAL */;
	CAMELAccessPointNameNI_t	*cAMELAccessPointNameNI	/* OPTIONAL */;
	CAMELAccessPointNameOI_t	*cAMELAccessPointNameOI	/* OPTIONAL */;
	NumberOfDPEncountered_t	*numberOfDPEncountered	/* OPTIONAL */;
	LevelOfCAMELService_t	*levelOfCAMELService	/* OPTIONAL */;
	FreeFormatData_t	*freeFormatData	/* OPTIONAL */;
	FFDAppendIndicator_t	*fFDAppendIndicator	/* OPTIONAL */;
	
	/* Presence bitmask: ASN_SET_ISPRESENT(pCAMELInformationPDP, CAMELInformationPDP_PR_x) */
	unsigned int _presence_map
		[((9+(8*sizeof(unsigned int))-1)/(8*sizeof(unsigned int)))];
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CAMELInformationPDP_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CAMELInformationPDP;

#ifdef __cplusplus
}
#endif

#endif	/* _CAMELInformationPDP_H_ */
#include <asn_internal.h>
