/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "CDR"
 * 	found in "../cdr.asn1"
 * 	`asn1c -fskeletons-copy -fnative-types`
 */

#include "CAMELSMSInformation.h"

static asn_TYPE_member_t asn_MBR_CAMELSMSInformation_1[] = {
	{ ATF_POINTER, 7, offsetof(struct CAMELSMSInformation, gsm_SCFAddress),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Gsm_SCFAddress,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"gsm-SCFAddress"
		},
	{ ATF_POINTER, 6, offsetof(struct CAMELSMSInformation, serviceKey),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ServiceKey,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"serviceKey"
		},
	{ ATF_POINTER, 5, offsetof(struct CAMELSMSInformation, defaultSMSHandling),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DefaultSMS_Handling,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"defaultSMSHandling"
		},
	{ ATF_POINTER, 4, offsetof(struct CAMELSMSInformation, freeFormatData),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_FreeFormatData,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"freeFormatData"
		},
	{ ATF_POINTER, 3, offsetof(struct CAMELSMSInformation, callingPartyNumber),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CallingNumber,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"callingPartyNumber"
		},
	{ ATF_POINTER, 2, offsetof(struct CAMELSMSInformation, destinationSubscriberNumber),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CalledNumber,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"destinationSubscriberNumber"
		},
	{ ATF_POINTER, 1, offsetof(struct CAMELSMSInformation, cAMELSMSCAddress),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AddressString,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"cAMELSMSCAddress"
		},
};
static ber_tlv_tag_t asn_DEF_CAMELSMSInformation_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (17 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_CAMELSMSInformation_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 0, 0, 0 }, /* gsm-SCFAddress at 267 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 1, 0, 0 }, /* serviceKey at 268 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 2, 0, 0 }, /* defaultSMSHandling at 269 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 3, 0, 0 }, /* freeFormatData at 270 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 4, 0, 0 }, /* callingPartyNumber at 271 */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 5, 0, 0 }, /* destinationSubscriberNumber at 272 */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 6, 0, 0 } /* cAMELSMSCAddress at 273 */
};
static uint8_t asn_MAP_CAMELSMSInformation_mmap_1[(7 + (8 * sizeof(unsigned int)) - 1) / 8] = {
	(0 << 7) | (0 << 6) | (0 << 5) | (0 << 4) | (0 << 3) | (0 << 2) | (0 << 1)
};
static asn_SET_specifics_t asn_SPC_CAMELSMSInformation_specs_1 = {
	sizeof(struct CAMELSMSInformation),
	offsetof(struct CAMELSMSInformation, _asn_ctx),
	offsetof(struct CAMELSMSInformation, _presence_map),
	asn_MAP_CAMELSMSInformation_tag2el_1,
	7,	/* Count of tags in the map */
	asn_MAP_CAMELSMSInformation_tag2el_1,	/* Same as above */
	7,	/* Count of tags in the CXER map */
	0,	/* Whether extensible */
	(unsigned int *)asn_MAP_CAMELSMSInformation_mmap_1	/* Mandatory elements map */
};
asn_TYPE_descriptor_t asn_DEF_CAMELSMSInformation = {
	"CAMELSMSInformation",
	"CAMELSMSInformation",
	SET_free,
	SET_print,
	SET_constraint,
	SET_decode_ber,
	SET_encode_der,
	SET_decode_xer,
	SET_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_CAMELSMSInformation_tags_1,
	sizeof(asn_DEF_CAMELSMSInformation_tags_1)
		/sizeof(asn_DEF_CAMELSMSInformation_tags_1[0]), /* 1 */
	asn_DEF_CAMELSMSInformation_tags_1,	/* Same as above */
	sizeof(asn_DEF_CAMELSMSInformation_tags_1)
		/sizeof(asn_DEF_CAMELSMSInformation_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_CAMELSMSInformation_1,
	7,	/* Elements count */
	&asn_SPC_CAMELSMSInformation_specs_1	/* Additional specs */
};

