/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "CDR"
 * 	found in "../cdr.asn1"
 * 	`asn1c -fskeletons-copy -fnative-types`
 */

#ifndef	_CAMELAccessPointNameOI_H_
#define	_CAMELAccessPointNameOI_H_


#include <asn_application.h>

/* Including external dependencies */
#include "AccessPointNameOI.h"

#ifdef __cplusplus
extern "C" {
#endif

/* CAMELAccessPointNameOI */
typedef AccessPointNameOI_t	 CAMELAccessPointNameOI_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CAMELAccessPointNameOI;
asn_struct_free_f CAMELAccessPointNameOI_free;
asn_struct_print_f CAMELAccessPointNameOI_print;
asn_constr_check_f CAMELAccessPointNameOI_constraint;
ber_type_decoder_f CAMELAccessPointNameOI_decode_ber;
der_type_encoder_f CAMELAccessPointNameOI_encode_der;
xer_type_decoder_f CAMELAccessPointNameOI_decode_xer;
xer_type_encoder_f CAMELAccessPointNameOI_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _CAMELAccessPointNameOI_H_ */
#include <asn_internal.h>
