/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "CDR"
 * 	found in "../cdr.asn1"
 * 	`asn1c -fskeletons-copy -fnative-types`
 */

#ifndef	_CAMELDestinationNumber_H_
#define	_CAMELDestinationNumber_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DestinationRoutingAddress.h"

#ifdef __cplusplus
extern "C" {
#endif

/* CAMELDestinationNumber */
typedef DestinationRoutingAddress_t	 CAMELDestinationNumber_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CAMELDestinationNumber;
asn_struct_free_f CAMELDestinationNumber_free;
asn_struct_print_f CAMELDestinationNumber_print;
asn_constr_check_f CAMELDestinationNumber_constraint;
ber_type_decoder_f CAMELDestinationNumber_decode_ber;
der_type_encoder_f CAMELDestinationNumber_encode_der;
xer_type_decoder_f CAMELDestinationNumber_decode_xer;
xer_type_encoder_f CAMELDestinationNumber_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _CAMELDestinationNumber_H_ */
#include <asn_internal.h>
