/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "CDR"
 * 	found in "../cdr.asn1"
 * 	`asn1c -fskeletons-copy -fnative-types`
 */

#ifndef	_CAMELSMSInformation_H_
#define	_CAMELSMSInformation_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Gsm-SCFAddress.h"
#include "ServiceKey.h"
#include "DefaultSMS-Handling.h"
#include "FreeFormatData.h"
#include "CallingNumber.h"
#include "CalledNumber.h"
#include "AddressString.h"
#include <constr_SET.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */

/*
 * Method of determining the components presence
 */
typedef enum CAMELSMSInformation_PR {
	CAMELSMSInformation_PR_gsm_SCFAddress,	/* Member gsm_SCFAddress is present */
	CAMELSMSInformation_PR_serviceKey,	/* Member serviceKey is present */
	CAMELSMSInformation_PR_defaultSMSHandling,	/* Member defaultSMSHandling is present */
	CAMELSMSInformation_PR_freeFormatData,	/* Member freeFormatData is present */
	CAMELSMSInformation_PR_callingPartyNumber,	/* Member callingPartyNumber is present */
	CAMELSMSInformation_PR_destinationSubscriberNumber,	/* Member destinationSubscriberNumber is present */
	CAMELSMSInformation_PR_cAMELSMSCAddress,	/* Member cAMELSMSCAddress is present */
} CAMELSMSInformation_PR;

/* CAMELSMSInformation */
typedef struct CAMELSMSInformation {
	Gsm_SCFAddress_t	*gsm_SCFAddress	/* OPTIONAL */;
	ServiceKey_t	*serviceKey	/* OPTIONAL */;
	DefaultSMS_Handling_t	*defaultSMSHandling	/* OPTIONAL */;
	FreeFormatData_t	*freeFormatData	/* OPTIONAL */;
	CallingNumber_t	*callingPartyNumber	/* OPTIONAL */;
	CalledNumber_t	*destinationSubscriberNumber	/* OPTIONAL */;
	AddressString_t	*cAMELSMSCAddress	/* OPTIONAL */;
	
	/* Presence bitmask: ASN_SET_ISPRESENT(pCAMELSMSInformation, CAMELSMSInformation_PR_x) */
	unsigned int _presence_map
		[((7+(8*sizeof(unsigned int))-1)/(8*sizeof(unsigned int)))];
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CAMELSMSInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CAMELSMSInformation;

#ifdef __cplusplus
}
#endif

#endif	/* _CAMELSMSInformation_H_ */
#include <asn_internal.h>
