/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "CDR"
 * 	found in "../cdr.asn1"
 * 	`asn1c -fskeletons-copy -fnative-types`
 */

#ifndef	_CAMELInformation_H_
#define	_CAMELInformation_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ConnectedNumber.h"
#include "RoamingNumber.h"
#include "TimeStamp.h"
#include "CallDuration.h"
#include "DataVolume.h"
#include "CAMELInitCFIndicator.h"
#include "CauseForTerm.h"
#include "FreeFormatData.h"
#include <BOOLEAN.h>
#include <constr_SET.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */

/*
 * Method of determining the components presence
 */
typedef enum CAMELInformation_PR {
	CAMELInformation_PR_cAMELDestinationNumber,	/* Member cAMELDestinationNumber is present */
	CAMELInformation_PR_connectedNumber,	/* Member connectedNumber is present */
	CAMELInformation_PR_roamingNumber,	/* Member roamingNumber is present */
	CAMELInformation_PR_mscOutgoingTKGP,	/* Member mscOutgoingTKGP is present */
	CAMELInformation_PR_seizureTime,	/* Member seizureTime is present */
	CAMELInformation_PR_answerTime,	/* Member answerTime is present */
	CAMELInformation_PR_releaseTime,	/* Member releaseTime is present */
	CAMELInformation_PR_callDuration,	/* Member callDuration is present */
	CAMELInformation_PR_dataVolume,	/* Member dataVolume is present */
	CAMELInformation_PR_cAMELInitCFIndicator,	/* Member cAMELInitCFIndicator is present */
	CAMELInformation_PR_causeForTerm,	/* Member causeForTerm is present */
	CAMELInformation_PR_cAMELModification,	/* Member cAMELModification is present */
	CAMELInformation_PR_freeFormatData,	/* Member freeFormatData is present */
	CAMELInformation_PR_diagnostics,	/* Member diagnostics is present */
	CAMELInformation_PR_freeFormatDataAppend,	/* Member freeFormatDataAppend is present */
	CAMELInformation_PR_freeFormatData_2,	/* Member freeFormatData_2 is present */
	CAMELInformation_PR_freeFormatDataAppend_2,	/* Member freeFormatDataAppend_2 is present */
} CAMELInformation_PR;

/* Forward declarations */
struct DestinationRoutingAddress;
struct TrunkGroup;
struct ChangedParameters;
struct Diagnostics;

/* CAMELInformation */
typedef struct CAMELInformation {
	struct DestinationRoutingAddress	*cAMELDestinationNumber	/* OPTIONAL */;
	ConnectedNumber_t	*connectedNumber	/* OPTIONAL */;
	RoamingNumber_t	*roamingNumber	/* OPTIONAL */;
	struct TrunkGroup	*mscOutgoingTKGP	/* OPTIONAL */;
	TimeStamp_t	*seizureTime	/* OPTIONAL */;
	TimeStamp_t	*answerTime	/* OPTIONAL */;
	TimeStamp_t	*releaseTime	/* OPTIONAL */;
	CallDuration_t	*callDuration	/* OPTIONAL */;
	DataVolume_t	*dataVolume	/* OPTIONAL */;
	CAMELInitCFIndicator_t	*cAMELInitCFIndicator	/* OPTIONAL */;
	CauseForTerm_t	*causeForTerm	/* OPTIONAL */;
	struct ChangedParameters	*cAMELModification	/* OPTIONAL */;
	FreeFormatData_t	*freeFormatData	/* OPTIONAL */;
	struct Diagnostics	*diagnostics	/* OPTIONAL */;
	BOOLEAN_t	*freeFormatDataAppend	/* OPTIONAL */;
	FreeFormatData_t	*freeFormatData_2	/* OPTIONAL */;
	BOOLEAN_t	*freeFormatDataAppend_2	/* OPTIONAL */;
	
	/* Presence bitmask: ASN_SET_ISPRESENT(pCAMELInformation, CAMELInformation_PR_x) */
	unsigned int _presence_map
		[((17+(8*sizeof(unsigned int))-1)/(8*sizeof(unsigned int)))];
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CAMELInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CAMELInformation;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "CAMELDestinationNumber.h"
#include "TrunkGroup.h"
#include "ChangedParameters.h"
#include "Diagnostics.h"

#endif	/* _CAMELInformation_H_ */
#include <asn_internal.h>
