/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "CDR"
 * 	found in "../cdr.asn1"
 * 	`asn1c -fskeletons-copy -fnative-types`
 */

#ifndef	_CAMELModificationParameters_H_
#define	_CAMELModificationParameters_H_


#include <asn_application.h>

/* Including external dependencies */
#include "CallingNumber.h"
#include "CallingPartyCategory.h"
#include "OriginalCalledNumber.h"
#include "RedirectingNumber.h"
#include "NumberOfForwarding.h"
#include <constr_SET.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */

/*
 * Method of determining the components presence
 */
typedef enum CAMELModificationParameters_PR {
	CAMELModificationParameters_PR_callingPartyNumber,	/* Member callingPartyNumber is present */
	CAMELModificationParameters_PR_callingPartyCategory,	/* Member callingPartyCategory is present */
	CAMELModificationParameters_PR_originalCalledPartyNumber,	/* Member originalCalledPartyNumber is present */
	CAMELModificationParameters_PR_genericNumbers,	/* Member genericNumbers is present */
	CAMELModificationParameters_PR_redirectingPartyNumber,	/* Member redirectingPartyNumber is present */
	CAMELModificationParameters_PR_redirectionCounter,	/* Member redirectionCounter is present */
} CAMELModificationParameters_PR;

/* Forward declarations */
struct GenericNumbers;

/* CAMELModificationParameters */
typedef struct CAMELModificationParameters {
	CallingNumber_t	*callingPartyNumber	/* OPTIONAL */;
	CallingPartyCategory_t	*callingPartyCategory	/* OPTIONAL */;
	OriginalCalledNumber_t	*originalCalledPartyNumber	/* OPTIONAL */;
	struct GenericNumbers	*genericNumbers	/* OPTIONAL */;
	RedirectingNumber_t	*redirectingPartyNumber	/* OPTIONAL */;
	NumberOfForwarding_t	*redirectionCounter	/* OPTIONAL */;
	
	/* Presence bitmask: ASN_SET_ISPRESENT(pCAMELModificationParameters, CAMELModificationParameters_PR_x) */
	unsigned int _presence_map
		[((6+(8*sizeof(unsigned int))-1)/(8*sizeof(unsigned int)))];
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CAMELModificationParameters_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CAMELModificationParameters;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "GenericNumbers.h"

#endif	/* _CAMELModificationParameters_H_ */
#include <asn_internal.h>
