/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "CDR"
 * 	found in "../cdr.asn1"
 * 	`asn1c -fskeletons-copy -fnative-types`
 */

#ifndef	_CauseForTerm_H_
#define	_CauseForTerm_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CauseForTerm {
	CauseForTerm_normalRelease	= 0,
	CauseForTerm_partialRecord	= 1,
	CauseForTerm_partialRecordCallReestablishment	= 2,
	CauseForTerm_unsuccessfulCallAttempt	= 3,
	CauseForTerm_stableCallAbnormalTermination	= 4,
	CauseForTerm_cAMELInitCallRelease	= 5
} e_CauseForTerm;

/* CauseForTerm */
typedef long	 CauseForTerm_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CauseForTerm;
asn_struct_free_f CauseForTerm_free;
asn_struct_print_f CauseForTerm_print;
asn_constr_check_f CauseForTerm_constraint;
ber_type_decoder_f CauseForTerm_decode_ber;
der_type_encoder_f CauseForTerm_encode_der;
xer_type_decoder_f CauseForTerm_decode_xer;
xer_type_encoder_f CauseForTerm_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _CauseForTerm_H_ */
#include <asn_internal.h>
