/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "CDR"
 * 	found in "../cdr.asn1"
 * 	`asn1c -fskeletons-copy -fnative-types`
 */

#include "ChangedParameters.h"

static asn_TYPE_member_t asn_MBR_ChangedParameters_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ChangedParameters, changeFlags),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ChangeFlags,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"changeFlags"
		},
	{ ATF_POINTER, 1, offsetof(struct ChangedParameters, changeList),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CAMELModificationParameters,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"changeList"
		},
};
static ber_tlv_tag_t asn_DEF_ChangedParameters_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (17 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_ChangedParameters_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* changeFlags at 325 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* changeList at 326 */
};
static uint8_t asn_MAP_ChangedParameters_mmap_1[(2 + (8 * sizeof(unsigned int)) - 1) / 8] = {
	(1 << 7) | (0 << 6)
};
static asn_SET_specifics_t asn_SPC_ChangedParameters_specs_1 = {
	sizeof(struct ChangedParameters),
	offsetof(struct ChangedParameters, _asn_ctx),
	offsetof(struct ChangedParameters, _presence_map),
	asn_MAP_ChangedParameters_tag2el_1,
	2,	/* Count of tags in the map */
	asn_MAP_ChangedParameters_tag2el_1,	/* Same as above */
	2,	/* Count of tags in the CXER map */
	0,	/* Whether extensible */
	(unsigned int *)asn_MAP_ChangedParameters_mmap_1	/* Mandatory elements map */
};
asn_TYPE_descriptor_t asn_DEF_ChangedParameters = {
	"ChangedParameters",
	"ChangedParameters",
	SET_free,
	SET_print,
	SET_constraint,
	SET_decode_ber,
	SET_encode_der,
	SET_decode_xer,
	SET_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_ChangedParameters_tags_1,
	sizeof(asn_DEF_ChangedParameters_tags_1)
		/sizeof(asn_DEF_ChangedParameters_tags_1[0]), /* 1 */
	asn_DEF_ChangedParameters_tags_1,	/* Same as above */
	sizeof(asn_DEF_ChangedParameters_tags_1)
		/sizeof(asn_DEF_ChangedParameters_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_ChangedParameters_1,
	2,	/* Elements count */
	&asn_SPC_ChangedParameters_specs_1	/* Additional specs */
};

