/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "CDR"
 * 	found in "../cdr.asn1"
 * 	`asn1c -fskeletons-copy -fnative-types`
 */

#ifndef	_ChangeOfClassmark_H_
#define	_ChangeOfClassmark_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Classmark.h"
#include "TimeStamp.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ChangeOfClassmark */
typedef struct ChangeOfClassmark {
	Classmark_t	 classmark;
	TimeStamp_t	 changeTime;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ChangeOfClassmark_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ChangeOfClassmark;

#ifdef __cplusplus
}
#endif

#endif	/* _ChangeOfClassmark_H_ */
#include <asn_internal.h>
