/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "CDR"
 * 	found in "../cdr.asn1"
 * 	`asn1c -fskeletons-copy -fnative-types`
 */

#ifndef	_ChannelCoding_H_
#define	_ChannelCoding_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ChannelCoding {
	ChannelCoding_tchF4800	= 1,
	ChannelCoding_tchF9600	= 2,
	ChannelCoding_tchF14400	= 3
} e_ChannelCoding;

/* ChannelCoding */
typedef long	 ChannelCoding_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ChannelCoding;
asn_struct_free_f ChannelCoding_free;
asn_struct_print_f ChannelCoding_print;
asn_constr_check_f ChannelCoding_constraint;
ber_type_decoder_f ChannelCoding_decode_ber;
der_type_encoder_f ChannelCoding_encode_der;
xer_type_decoder_f ChannelCoding_decode_xer;
xer_type_encoder_f ChannelCoding_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _ChannelCoding_H_ */
#include <asn_internal.h>
