/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "CDR"
 * 	found in "../cdr.asn1"
 * 	`asn1c -fskeletons-copy -fnative-types`
 */

#ifndef	_ChangeOfCharCondition_H_
#define	_ChangeOfCharCondition_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DataVolumeGPRS.h"
#include "ChangeCondition.h"
#include "TimeStamp.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct QoSInformation;

/* ChangeOfCharCondition */
typedef struct ChangeOfCharCondition {
	struct QoSInformation	*qosRequested	/* OPTIONAL */;
	struct QoSInformation	*qosNegotiated	/* OPTIONAL */;
	DataVolumeGPRS_t	 dataVolumeGPRSUplink;
	DataVolumeGPRS_t	 dataVolumeGPRSDownlink;
	ChangeCondition_t	 changeCondition;
	TimeStamp_t	 changeTime;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ChangeOfCharCondition_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ChangeOfCharCondition;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "QoSInformation.h"

#endif	/* _ChangeOfCharCondition_H_ */
#include <asn_internal.h>
