/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "CDR"
 * 	found in "../cdr.asn1"
 * 	`asn1c -fskeletons-copy -fnative-types`
 */

#ifndef	_ChangeCondition_H_
#define	_ChangeCondition_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ChangeCondition {
	ChangeCondition_qoSChange	= 0,
	ChangeCondition_tariffTime	= 1,
	ChangeCondition_recordClosure	= 2
} e_ChangeCondition;

/* ChangeCondition */
typedef long	 ChangeCondition_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ChangeCondition;
asn_struct_free_f ChangeCondition_free;
asn_struct_print_f ChangeCondition_print;
asn_constr_check_f ChangeCondition_constraint;
ber_type_decoder_f ChangeCondition_decode_ber;
der_type_encoder_f ChangeCondition_encode_der;
xer_type_decoder_f ChangeCondition_decode_xer;
xer_type_encoder_f ChangeCondition_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _ChangeCondition_H_ */
#include <asn_internal.h>
