/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "CDR"
 * 	found in "../cdr.asn1"
 * 	`asn1c -fskeletons-copy -fnative-types`
 */

#ifndef	_ChangeOfRadioChannel_H_
#define	_ChangeOfRadioChannel_H_


#include <asn_application.h>

/* Including external dependencies */
#include "TrafficChannel.h"
#include "TimeStamp.h"
#include "SpeechVersionIdentifier.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ChangeOfRadioChannel */
typedef struct ChangeOfRadioChannel {
	TrafficChannel_t	 radioChannel;
	TimeStamp_t	 changeTime;
	SpeechVersionIdentifier_t	*speechVersionUsed	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ChangeOfRadioChannel_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ChangeOfRadioChannel;

#ifdef __cplusplus
}
#endif

#endif	/* _ChangeOfRadioChannel_H_ */
#include <asn_internal.h>
