/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "CDR"
 * 	found in "../cdr.asn1"
 * 	`asn1c -fskeletons-copy -fnative-types`
 */

#include "ChangeOfCharCondition.h"

static asn_TYPE_member_t asn_MBR_ChangeOfCharCondition_1[] = {
	{ ATF_POINTER, 2, offsetof(struct ChangeOfCharCondition, qosRequested),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_QoSInformation,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"qosRequested"
		},
	{ ATF_POINTER, 1, offsetof(struct ChangeOfCharCondition, qosNegotiated),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_QoSInformation,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"qosNegotiated"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ChangeOfCharCondition, dataVolumeGPRSUplink),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DataVolumeGPRS,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"dataVolumeGPRSUplink"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ChangeOfCharCondition, dataVolumeGPRSDownlink),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DataVolumeGPRS,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"dataVolumeGPRSDownlink"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ChangeOfCharCondition, changeCondition),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ChangeCondition,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"changeCondition"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ChangeOfCharCondition, changeTime),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TimeStamp,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"changeTime"
		},
};
static ber_tlv_tag_t asn_DEF_ChangeOfCharCondition_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_ChangeOfCharCondition_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 0, 0, 0 }, /* qosRequested at 489 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 1, 0, 0 }, /* qosNegotiated at 490 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 2, 0, 0 }, /* dataVolumeGPRSUplink at 491 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 3, 0, 0 }, /* dataVolumeGPRSDownlink at 492 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 4, 0, 0 }, /* changeCondition at 493 */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 5, 0, 0 } /* changeTime at 495 */
};
static asn_SEQUENCE_specifics_t asn_SPC_ChangeOfCharCondition_specs_1 = {
	sizeof(struct ChangeOfCharCondition),
	offsetof(struct ChangeOfCharCondition, _asn_ctx),
	asn_MAP_ChangeOfCharCondition_tag2el_1,
	6,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_ChangeOfCharCondition = {
	"ChangeOfCharCondition",
	"ChangeOfCharCondition",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_ChangeOfCharCondition_tags_1,
	sizeof(asn_DEF_ChangeOfCharCondition_tags_1)
		/sizeof(asn_DEF_ChangeOfCharCondition_tags_1[0]), /* 1 */
	asn_DEF_ChangeOfCharCondition_tags_1,	/* Same as above */
	sizeof(asn_DEF_ChangeOfCharCondition_tags_1)
		/sizeof(asn_DEF_ChangeOfCharCondition_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_ChangeOfCharCondition_1,
	6,	/* Elements count */
	&asn_SPC_ChangeOfCharCondition_specs_1	/* Additional specs */
};

