/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "CDR"
 * 	found in "../cdr.asn1"
 * 	`asn1c -fskeletons-copy -fnative-types`
 */

#include "ChangeOfRadioChannel.h"

static asn_TYPE_member_t asn_MBR_ChangeOfRadioChannel_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ChangeOfRadioChannel, radioChannel),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TrafficChannel,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"radioChannel"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ChangeOfRadioChannel, changeTime),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TimeStamp,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"changeTime"
		},
	{ ATF_POINTER, 1, offsetof(struct ChangeOfRadioChannel, speechVersionUsed),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SpeechVersionIdentifier,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"speechVersionUsed"
		},
};
static ber_tlv_tag_t asn_DEF_ChangeOfRadioChannel_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_ChangeOfRadioChannel_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* radioChannel at 347 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* changeTime at 348 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* speechVersionUsed at 349 */
};
static asn_SEQUENCE_specifics_t asn_SPC_ChangeOfRadioChannel_specs_1 = {
	sizeof(struct ChangeOfRadioChannel),
	offsetof(struct ChangeOfRadioChannel, _asn_ctx),
	asn_MAP_ChangeOfRadioChannel_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_ChangeOfRadioChannel = {
	"ChangeOfRadioChannel",
	"ChangeOfRadioChannel",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_ChangeOfRadioChannel_tags_1,
	sizeof(asn_DEF_ChangeOfRadioChannel_tags_1)
		/sizeof(asn_DEF_ChangeOfRadioChannel_tags_1[0]), /* 1 */
	asn_DEF_ChangeOfRadioChannel_tags_1,	/* Same as above */
	sizeof(asn_DEF_ChangeOfRadioChannel_tags_1)
		/sizeof(asn_DEF_ChangeOfRadioChannel_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_ChangeOfRadioChannel_1,
	3,	/* Elements count */
	&asn_SPC_ChangeOfRadioChannel_specs_1	/* Additional specs */
};

