/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "CDR"
 * 	found in "../cdr.asn1"
 * 	`asn1c -fskeletons-copy -fnative-types`
 */

#ifndef	_ChangedParameters_H_
#define	_ChangedParameters_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ChangeFlags.h"
#include <constr_SET.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */

/*
 * Method of determining the components presence
 */
typedef enum ChangedParameters_PR {
	ChangedParameters_PR_changeFlags,	/* Member changeFlags is present */
	ChangedParameters_PR_changeList,	/* Member changeList is present */
} ChangedParameters_PR;

/* Forward declarations */
struct CAMELModificationParameters;

/* ChangedParameters */
typedef struct ChangedParameters {
	ChangeFlags_t	 changeFlags;
	struct CAMELModificationParameters	*changeList	/* OPTIONAL */;
	
	/* Presence bitmask: ASN_SET_ISPRESENT(pChangedParameters, ChangedParameters_PR_x) */
	unsigned int _presence_map
		[((2+(8*sizeof(unsigned int))-1)/(8*sizeof(unsigned int)))];
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ChangedParameters_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ChangedParameters;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "CAMELModificationParameters.h"

#endif	/* _ChangedParameters_H_ */
#include <asn_internal.h>
