/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "CDR"
 * 	found in "../cdr.asn1"
 * 	`asn1c -fskeletons-copy -fnative-types`
 */

#ifndef	_Classmark_H_
#define	_Classmark_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Classmark */
typedef OCTET_STRING_t	 Classmark_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Classmark;
asn_struct_free_f Classmark_free;
asn_struct_print_f Classmark_print;
asn_constr_check_f Classmark_constraint;
ber_type_decoder_f Classmark_decode_ber;
der_type_encoder_f Classmark_encode_der;
xer_type_decoder_f Classmark_decode_xer;
xer_type_encoder_f Classmark_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _Classmark_H_ */
#include <asn_internal.h>
