/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "CDR"
 * 	found in "../cdr.asn1"
 * 	`asn1c -fskeletons-copy -fnative-types`
 */

#ifndef	_ConnectedNumber_H_
#define	_ConnectedNumber_H_


#include <asn_application.h>

/* Including external dependencies */
#include "BCDDirectoryNumber.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ConnectedNumber */
typedef BCDDirectoryNumber_t	 ConnectedNumber_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ConnectedNumber;
asn_struct_free_f ConnectedNumber_free;
asn_struct_print_f ConnectedNumber_print;
asn_constr_check_f ConnectedNumber_constraint;
ber_type_decoder_f ConnectedNumber_decode_ber;
der_type_encoder_f ConnectedNumber_encode_der;
xer_type_decoder_f ConnectedNumber_decode_xer;
xer_type_encoder_f ConnectedNumber_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _ConnectedNumber_H_ */
#include <asn_internal.h>
