/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "CDR"
 * 	found in "../cdr.asn1"
 * 	`asn1c -fskeletons-copy -fnative-types`
 */

#ifndef	_DataVolumeGPRS_H_
#define	_DataVolumeGPRS_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DataVolumeGPRS */
typedef long	 DataVolumeGPRS_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DataVolumeGPRS;
asn_struct_free_f DataVolumeGPRS_free;
asn_struct_print_f DataVolumeGPRS_print;
asn_constr_check_f DataVolumeGPRS_constraint;
ber_type_decoder_f DataVolumeGPRS_decode_ber;
der_type_encoder_f DataVolumeGPRS_encode_der;
xer_type_decoder_f DataVolumeGPRS_decode_xer;
xer_type_encoder_f DataVolumeGPRS_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _DataVolumeGPRS_H_ */
#include <asn_internal.h>
