/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "CDR"
 * 	found in "../cdr.asn1"
 * 	`asn1c -fskeletons-copy -fnative-types`
 */

#ifndef	_EParameter_H_
#define	_EParameter_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* EParameter */
typedef long	 EParameter_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EParameter;
asn_struct_free_f EParameter_free;
asn_struct_print_f EParameter_print;
asn_constr_check_f EParameter_constraint;
ber_type_decoder_f EParameter_decode_ber;
der_type_encoder_f EParameter_encode_der;
xer_type_decoder_f EParameter_decode_xer;
xer_type_encoder_f EParameter_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _EParameter_H_ */
#include <asn_internal.h>
