/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "CDR"
 * 	found in "../cdr.asn1"
 * 	`asn1c -fskeletons-copy -fnative-types`
 */

#ifndef	_EquipmentType_H_
#define	_EquipmentType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum EquipmentType {
	EquipmentType_conferenceBridge	= 0
} e_EquipmentType;

/* EquipmentType */
typedef long	 EquipmentType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EquipmentType;
asn_struct_free_f EquipmentType_free;
asn_struct_print_f EquipmentType_print;
asn_constr_check_f EquipmentType_constraint;
ber_type_decoder_f EquipmentType_decode_ber;
der_type_encoder_f EquipmentType_encode_der;
xer_type_decoder_f EquipmentType_decode_xer;
xer_type_encoder_f EquipmentType_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _EquipmentType_H_ */
#include <asn_internal.h>
