/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "CDR"
 * 	found in "../cdr.asn1"
 * 	`asn1c -fskeletons-copy -fnative-types`
 */

#ifndef	_FFDAppendIndicator_H_
#define	_FFDAppendIndicator_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BOOLEAN.h>

#ifdef __cplusplus
extern "C" {
#endif

/* FFDAppendIndicator */
typedef BOOLEAN_t	 FFDAppendIndicator_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FFDAppendIndicator;
asn_struct_free_f FFDAppendIndicator_free;
asn_struct_print_f FFDAppendIndicator_print;
asn_constr_check_f FFDAppendIndicator_constraint;
ber_type_decoder_f FFDAppendIndicator_decode_ber;
der_type_encoder_f FFDAppendIndicator_encode_der;
xer_type_decoder_f FFDAppendIndicator_decode_xer;
xer_type_encoder_f FFDAppendIndicator_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _FFDAppendIndicator_H_ */
#include <asn_internal.h>
