/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "CDR"
 * 	found in "../cdr.asn1"
 * 	`asn1c -fskeletons-copy -fnative-types`
 */

#ifndef	_Fnur_H_
#define	_Fnur_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Fnur {
	Fnur_fnurNotApplicable	= 0,
	Fnur_fnur9600_BitsPerSecond	= 1,
	Fnur_fnur14400BitsPerSecond	= 2,
	Fnur_fnur19200BitsPerSecond	= 3,
	Fnur_fnur28800BitsPerSecond	= 4,
	Fnur_fnur38400BitsPerSecond	= 5,
	Fnur_fnur48000BitsPerSecond	= 6,
	Fnur_fnur56000BitsPerSecond	= 7,
	Fnur_fnur64000BitsPerSecond	= 8,
	Fnur_fnur33600BitsPerSecond	= 9,
	Fnur_fnur32000BitsPerSecond	= 10,
	Fnur_fnur31200BitsPerSecond	= 11
} e_Fnur;

/* Fnur */
typedef long	 Fnur_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Fnur;
asn_struct_free_f Fnur_free;
asn_struct_print_f Fnur_print;
asn_constr_check_f Fnur_constraint;
ber_type_decoder_f Fnur_decode_ber;
der_type_encoder_f Fnur_encode_der;
xer_type_decoder_f Fnur_decode_xer;
xer_type_encoder_f Fnur_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _Fnur_H_ */
#include <asn_internal.h>
