/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "CDR"
 * 	found in "../cdr.asn1"
 * 	`asn1c -fskeletons-copy -fnative-types`
 */

#include "GGSNPDPRecord.h"

static asn_TYPE_member_t asn_MBR_sgsnAddress_7[] = {
	{ ATF_POINTER, 0, 0,
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_GSNAddress,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_sgsnAddress_tags_7[] = {
	(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_sgsnAddress_specs_7 = {
	sizeof(struct GGSNPDPRecord__sgsnAddress),
	offsetof(struct GGSNPDPRecord__sgsnAddress, _asn_ctx),
	2,	/* XER encoding is XMLValueList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_sgsnAddress_7 = {
	"sgsnAddress",
	"sgsnAddress",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_sgsnAddress_tags_7,
	sizeof(asn_DEF_sgsnAddress_tags_7)
		/sizeof(asn_DEF_sgsnAddress_tags_7[0]) - 1, /* 1 */
	asn_DEF_sgsnAddress_tags_7,	/* Same as above */
	sizeof(asn_DEF_sgsnAddress_tags_7)
		/sizeof(asn_DEF_sgsnAddress_tags_7[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_sgsnAddress_7,
	1,	/* Single element */
	&asn_SPC_sgsnAddress_specs_7	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_listOfTrafficVolumes_13[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ChangeOfCharCondition,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_listOfTrafficVolumes_tags_13[] = {
	(ASN_TAG_CLASS_CONTEXT | (12 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_listOfTrafficVolumes_specs_13 = {
	sizeof(struct GGSNPDPRecord__listOfTrafficVolumes),
	offsetof(struct GGSNPDPRecord__listOfTrafficVolumes, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_listOfTrafficVolumes_13 = {
	"listOfTrafficVolumes",
	"listOfTrafficVolumes",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_listOfTrafficVolumes_tags_13,
	sizeof(asn_DEF_listOfTrafficVolumes_tags_13)
		/sizeof(asn_DEF_listOfTrafficVolumes_tags_13[0]) - 1, /* 1 */
	asn_DEF_listOfTrafficVolumes_tags_13,	/* Same as above */
	sizeof(asn_DEF_listOfTrafficVolumes_tags_13)
		/sizeof(asn_DEF_listOfTrafficVolumes_tags_13[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_listOfTrafficVolumes_13,
	1,	/* Single element */
	&asn_SPC_listOfTrafficVolumes_specs_13	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_GGSNPDPRecord_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct GGSNPDPRecord, recordType),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CallEventRecordType,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"recordType"
		},
	{ ATF_POINTER, 1, offsetof(struct GGSNPDPRecord, networkInitiation),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NetworkInitiatedPDPContext,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"networkInitiation"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct GGSNPDPRecord, servedIMSI),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_IMSI,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"servedIMSI"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct GGSNPDPRecord, ggsnAddress),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_GSNAddress,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"ggsnAddress"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct GGSNPDPRecord, chargingID),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ChargingID,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"chargingID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct GGSNPDPRecord, sgsnAddress),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		0,
		&asn_DEF_sgsnAddress_7,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"sgsnAddress"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct GGSNPDPRecord, accessPointNameNI),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AccessPointNameNI,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"accessPointNameNI"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct GGSNPDPRecord, pdpType),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PDPType,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"pdpType"
		},
	{ ATF_POINTER, 2, offsetof(struct GGSNPDPRecord, servedPDPAddress),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_PDPAddress,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"servedPDPAddress"
		},
	{ ATF_POINTER, 1, offsetof(struct GGSNPDPRecord, dynamicAddressFlag),
		(ASN_TAG_CLASS_CONTEXT | (11 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DynamicAddressFlag,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"dynamicAddressFlag"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct GGSNPDPRecord, listOfTrafficVolumes),
		(ASN_TAG_CLASS_CONTEXT | (12 << 2)),
		0,
		&asn_DEF_listOfTrafficVolumes_13,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"listOfTrafficVolumes"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct GGSNPDPRecord, recordOpeningTime),
		(ASN_TAG_CLASS_CONTEXT | (13 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TimeStamp,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"recordOpeningTime"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct GGSNPDPRecord, duration),
		(ASN_TAG_CLASS_CONTEXT | (14 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CallDuration,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"duration"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct GGSNPDPRecord, causeForRecClosing),
		(ASN_TAG_CLASS_CONTEXT | (15 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CauseForRecClosing,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"causeForRecClosing"
		},
	{ ATF_POINTER, 8, offsetof(struct GGSNPDPRecord, diagnostics),
		(ASN_TAG_CLASS_CONTEXT | (16 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_Diagnostics,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"diagnostics"
		},
	{ ATF_POINTER, 7, offsetof(struct GGSNPDPRecord, recordSequenceNumber),
		(ASN_TAG_CLASS_CONTEXT | (17 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"recordSequenceNumber"
		},
	{ ATF_POINTER, 6, offsetof(struct GGSNPDPRecord, nodeID),
		(ASN_TAG_CLASS_CONTEXT | (18 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NodeID,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"nodeID"
		},
	{ ATF_POINTER, 5, offsetof(struct GGSNPDPRecord, recordExtensions),
		(ASN_TAG_CLASS_CONTEXT | (19 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ManagementExtensions,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"recordExtensions"
		},
	{ ATF_POINTER, 4, offsetof(struct GGSNPDPRecord, localSequenceNumber),
		(ASN_TAG_CLASS_CONTEXT | (20 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LocalSequenceNumber,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"localSequenceNumber"
		},
	{ ATF_POINTER, 3, offsetof(struct GGSNPDPRecord, apnSelectionMode),
		(ASN_TAG_CLASS_CONTEXT | (21 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_APNSelectionMode,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"apnSelectionMode"
		},
	{ ATF_POINTER, 2, offsetof(struct GGSNPDPRecord, servedMSISDN),
		(ASN_TAG_CLASS_CONTEXT | (22 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MSISDN,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"servedMSISDN"
		},
	{ ATF_POINTER, 1, offsetof(struct GGSNPDPRecord, chargingCharacteristics),
		(ASN_TAG_CLASS_CONTEXT | (23 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ChargingCharacteristics,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"chargingCharacteristics"
		},
};
static ber_tlv_tag_t asn_DEF_GGSNPDPRecord_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (17 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_GGSNPDPRecord_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* recordType at 17 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* networkInitiation at 18 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 2, 0, 0 }, /* servedIMSI at 19 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 3, 0, 0 }, /* ggsnAddress at 20 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 4, 0, 0 }, /* chargingID at 21 */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 5, 0, 0 }, /* sgsnAddress at 22 */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 6, 0, 0 }, /* accessPointNameNI at 23 */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 7, 0, 0 }, /* pdpType at 24 */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 8, 0, 0 }, /* servedPDPAddress at 25 */
    { (ASN_TAG_CLASS_CONTEXT | (11 << 2)), 9, 0, 0 }, /* dynamicAddressFlag at 26 */
    { (ASN_TAG_CLASS_CONTEXT | (12 << 2)), 10, 0, 0 }, /* listOfTrafficVolumes at 27 */
    { (ASN_TAG_CLASS_CONTEXT | (13 << 2)), 11, 0, 0 }, /* recordOpeningTime at 28 */
    { (ASN_TAG_CLASS_CONTEXT | (14 << 2)), 12, 0, 0 }, /* duration at 29 */
    { (ASN_TAG_CLASS_CONTEXT | (15 << 2)), 13, 0, 0 }, /* causeForRecClosing at 30 */
    { (ASN_TAG_CLASS_CONTEXT | (16 << 2)), 14, 0, 0 }, /* diagnostics at 31 */
    { (ASN_TAG_CLASS_CONTEXT | (17 << 2)), 15, 0, 0 }, /* recordSequenceNumber at 32 */
    { (ASN_TAG_CLASS_CONTEXT | (18 << 2)), 16, 0, 0 }, /* nodeID at 33 */
    { (ASN_TAG_CLASS_CONTEXT | (19 << 2)), 17, 0, 0 }, /* recordExtensions at 34 */
    { (ASN_TAG_CLASS_CONTEXT | (20 << 2)), 18, 0, 0 }, /* localSequenceNumber at 35 */
    { (ASN_TAG_CLASS_CONTEXT | (21 << 2)), 19, 0, 0 }, /* apnSelectionMode at 36 */
    { (ASN_TAG_CLASS_CONTEXT | (22 << 2)), 20, 0, 0 }, /* servedMSISDN at 37 */
    { (ASN_TAG_CLASS_CONTEXT | (23 << 2)), 21, 0, 0 } /* chargingCharacteristics at 38 */
};
static uint8_t asn_MAP_GGSNPDPRecord_mmap_1[(22 + (8 * sizeof(unsigned int)) - 1) / 8] = {
	(1 << 7) | (0 << 6) | (1 << 5) | (1 << 4) | (1 << 3) | (1 << 2) | (1 << 1) | (1 << 0),
	(0 << 7) | (0 << 6) | (1 << 5) | (1 << 4) | (1 << 3) | (1 << 2) | (0 << 1) | (0 << 0),
	(0 << 7) | (0 << 6) | (0 << 5) | (0 << 4) | (0 << 3) | (0 << 2)
};
static asn_SET_specifics_t asn_SPC_GGSNPDPRecord_specs_1 = {
	sizeof(struct GGSNPDPRecord),
	offsetof(struct GGSNPDPRecord, _asn_ctx),
	offsetof(struct GGSNPDPRecord, _presence_map),
	asn_MAP_GGSNPDPRecord_tag2el_1,
	22,	/* Count of tags in the map */
	asn_MAP_GGSNPDPRecord_tag2el_1,	/* Same as above */
	22,	/* Count of tags in the CXER map */
	0,	/* Whether extensible */
	(unsigned int *)asn_MAP_GGSNPDPRecord_mmap_1	/* Mandatory elements map */
};
asn_TYPE_descriptor_t asn_DEF_GGSNPDPRecord = {
	"GGSNPDPRecord",
	"GGSNPDPRecord",
	SET_free,
	SET_print,
	SET_constraint,
	SET_decode_ber,
	SET_encode_der,
	SET_decode_xer,
	SET_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_GGSNPDPRecord_tags_1,
	sizeof(asn_DEF_GGSNPDPRecord_tags_1)
		/sizeof(asn_DEF_GGSNPDPRecord_tags_1[0]), /* 1 */
	asn_DEF_GGSNPDPRecord_tags_1,	/* Same as above */
	sizeof(asn_DEF_GGSNPDPRecord_tags_1)
		/sizeof(asn_DEF_GGSNPDPRecord_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_GGSNPDPRecord_1,
	22,	/* Elements count */
	&asn_SPC_GGSNPDPRecord_specs_1	/* Additional specs */
};

