/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "CDR"
 * 	found in "../cdr.asn1"
 * 	`asn1c -fskeletons-copy -fnative-types`
 */

#ifndef	_GGSNPDPRecord_H_
#define	_GGSNPDPRecord_H_


#include <asn_application.h>

/* Including external dependencies */
#include "CallEventRecordType.h"
#include "NetworkInitiatedPDPContext.h"
#include "IMSI.h"
#include "GSNAddress.h"
#include "ChargingID.h"
#include "AccessPointNameNI.h"
#include "PDPType.h"
#include "DynamicAddressFlag.h"
#include "TimeStamp.h"
#include "CallDuration.h"
#include "CauseForRecClosing.h"
#include <NativeInteger.h>
#include "NodeID.h"
#include "LocalSequenceNumber.h"
#include "APNSelectionMode.h"
#include "MSISDN.h"
#include "ChargingCharacteristics.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SET.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */

/*
 * Method of determining the components presence
 */
typedef enum GGSNPDPRecord_PR {
	GGSNPDPRecord_PR_recordType,	/* Member recordType is present */
	GGSNPDPRecord_PR_networkInitiation,	/* Member networkInitiation is present */
	GGSNPDPRecord_PR_servedIMSI,	/* Member servedIMSI is present */
	GGSNPDPRecord_PR_ggsnAddress,	/* Member ggsnAddress is present */
	GGSNPDPRecord_PR_chargingID,	/* Member chargingID is present */
	GGSNPDPRecord_PR_sgsnAddress,	/* Member sgsnAddress is present */
	GGSNPDPRecord_PR_accessPointNameNI,	/* Member accessPointNameNI is present */
	GGSNPDPRecord_PR_pdpType,	/* Member pdpType is present */
	GGSNPDPRecord_PR_servedPDPAddress,	/* Member servedPDPAddress is present */
	GGSNPDPRecord_PR_dynamicAddressFlag,	/* Member dynamicAddressFlag is present */
	GGSNPDPRecord_PR_listOfTrafficVolumes,	/* Member listOfTrafficVolumes is present */
	GGSNPDPRecord_PR_recordOpeningTime,	/* Member recordOpeningTime is present */
	GGSNPDPRecord_PR_duration,	/* Member duration is present */
	GGSNPDPRecord_PR_causeForRecClosing,	/* Member causeForRecClosing is present */
	GGSNPDPRecord_PR_diagnostics,	/* Member diagnostics is present */
	GGSNPDPRecord_PR_recordSequenceNumber,	/* Member recordSequenceNumber is present */
	GGSNPDPRecord_PR_nodeID,	/* Member nodeID is present */
	GGSNPDPRecord_PR_recordExtensions,	/* Member recordExtensions is present */
	GGSNPDPRecord_PR_localSequenceNumber,	/* Member localSequenceNumber is present */
	GGSNPDPRecord_PR_apnSelectionMode,	/* Member apnSelectionMode is present */
	GGSNPDPRecord_PR_servedMSISDN,	/* Member servedMSISDN is present */
	GGSNPDPRecord_PR_chargingCharacteristics,	/* Member chargingCharacteristics is present */
} GGSNPDPRecord_PR;

/* Forward declarations */
struct PDPAddress;
struct Diagnostics;
struct ManagementExtensions;
struct IPAddress;
struct ChangeOfCharCondition;

/* GGSNPDPRecord */
typedef struct GGSNPDPRecord {
	CallEventRecordType_t	 recordType;
	NetworkInitiatedPDPContext_t	*networkInitiation	/* OPTIONAL */;
	IMSI_t	 servedIMSI;
	GSNAddress_t	 ggsnAddress;
	ChargingID_t	 chargingID;
	struct GGSNPDPRecord__sgsnAddress {
		A_SEQUENCE_OF(struct IPAddress) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} sgsnAddress;
	AccessPointNameNI_t	 accessPointNameNI;
	PDPType_t	 pdpType;
	struct PDPAddress	*servedPDPAddress	/* OPTIONAL */;
	DynamicAddressFlag_t	*dynamicAddressFlag	/* OPTIONAL */;
	struct GGSNPDPRecord__listOfTrafficVolumes {
		A_SEQUENCE_OF(struct ChangeOfCharCondition) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} listOfTrafficVolumes;
	TimeStamp_t	 recordOpeningTime;
	CallDuration_t	 duration;
	CauseForRecClosing_t	 causeForRecClosing;
	struct Diagnostics	*diagnostics	/* OPTIONAL */;
	long	*recordSequenceNumber	/* OPTIONAL */;
	NodeID_t	*nodeID	/* OPTIONAL */;
	struct ManagementExtensions	*recordExtensions	/* OPTIONAL */;
	LocalSequenceNumber_t	*localSequenceNumber	/* OPTIONAL */;
	APNSelectionMode_t	*apnSelectionMode	/* OPTIONAL */;
	MSISDN_t	*servedMSISDN	/* OPTIONAL */;
	ChargingCharacteristics_t	*chargingCharacteristics	/* OPTIONAL */;
	
	/* Presence bitmask: ASN_SET_ISPRESENT(pGGSNPDPRecord, GGSNPDPRecord_PR_x) */
	unsigned int _presence_map
		[((22+(8*sizeof(unsigned int))-1)/(8*sizeof(unsigned int)))];
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GGSNPDPRecord_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GGSNPDPRecord;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "PDPAddress.h"
#include "Diagnostics.h"
#include "ManagementExtensions.h"
#include "GSNAddress.h"
#include "ChangeOfCharCondition.h"

#endif	/* _GGSNPDPRecord_H_ */
#include <asn_internal.h>
