/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "CDR"
 * 	found in "../cdr.asn1"
 * 	`asn1c -fskeletons-copy -fnative-types`
 */

#ifndef	_Gsm_SCFAddress_H_
#define	_Gsm_SCFAddress_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ISDN-AddressString.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Gsm-SCFAddress */
typedef ISDN_AddressString_t	 Gsm_SCFAddress_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Gsm_SCFAddress;
asn_struct_free_f Gsm_SCFAddress_free;
asn_struct_print_f Gsm_SCFAddress_print;
asn_constr_check_f Gsm_SCFAddress_constraint;
ber_type_decoder_f Gsm_SCFAddress_decode_ber;
der_type_encoder_f Gsm_SCFAddress_encode_der;
xer_type_decoder_f Gsm_SCFAddress_decode_xer;
xer_type_encoder_f Gsm_SCFAddress_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _Gsm_SCFAddress_H_ */
#include <asn_internal.h>
