/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "CDR"
 * 	found in "../cdr.asn1"
 * 	`asn1c -fskeletons-copy -fnative-types`
 */

#include "GSMQoSInformation.h"

static asn_TYPE_member_t asn_MBR_GSMQoSInformation_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct GSMQoSInformation, reliability),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_QoSReliability,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"reliability"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct GSMQoSInformation, delay),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_QoSDelay,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"delay"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct GSMQoSInformation, precedence),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_QoSPrecedence,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"precedence"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct GSMQoSInformation, peakThroughput),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_QoSPeakThroughput,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"peakThroughput"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct GSMQoSInformation, meanThroughput),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_QoSMeanThroughput,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"meanThroughput"
		},
};
static ber_tlv_tag_t asn_DEF_GSMQoSInformation_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_GSMQoSInformation_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* reliability at 1203 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* delay at 1204 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* precedence at 1205 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* peakThroughput at 1206 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* meanThroughput at 1208 */
};
static asn_SEQUENCE_specifics_t asn_SPC_GSMQoSInformation_specs_1 = {
	sizeof(struct GSMQoSInformation),
	offsetof(struct GSMQoSInformation, _asn_ctx),
	asn_MAP_GSMQoSInformation_tag2el_1,
	5,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_GSMQoSInformation = {
	"GSMQoSInformation",
	"GSMQoSInformation",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_GSMQoSInformation_tags_1,
	sizeof(asn_DEF_GSMQoSInformation_tags_1)
		/sizeof(asn_DEF_GSMQoSInformation_tags_1[0]), /* 1 */
	asn_DEF_GSMQoSInformation_tags_1,	/* Same as above */
	sizeof(asn_DEF_GSMQoSInformation_tags_1)
		/sizeof(asn_DEF_GSMQoSInformation_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_GSMQoSInformation_1,
	5,	/* Elements count */
	&asn_SPC_GSMQoSInformation_specs_1	/* Additional specs */
};

