/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "CDR"
 * 	found in "../cdr.asn1"
 * 	`asn1c -fskeletons-copy -fnative-types`
 */

#include "HeaderRecord.h"

static asn_TYPE_member_t asn_MBR_HeaderRecord_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct HeaderRecord, productionDateTime),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TimeStamp,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"productionDateTime"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct HeaderRecord, recordingEntity),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RecordingEntity,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"recordingEntity"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct HeaderRecord, extensions),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ManagementExtensions,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"extensions"
		},
};
static ber_tlv_tag_t asn_DEF_HeaderRecord_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_HeaderRecord_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* productionDateTime at 158 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* recordingEntity at 159 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* extensions at 161 */
};
static asn_SEQUENCE_specifics_t asn_SPC_HeaderRecord_specs_1 = {
	sizeof(struct HeaderRecord),
	offsetof(struct HeaderRecord, _asn_ctx),
	asn_MAP_HeaderRecord_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_HeaderRecord = {
	"HeaderRecord",
	"HeaderRecord",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_HeaderRecord_tags_1,
	sizeof(asn_DEF_HeaderRecord_tags_1)
		/sizeof(asn_DEF_HeaderRecord_tags_1[0]), /* 1 */
	asn_DEF_HeaderRecord_tags_1,	/* Same as above */
	sizeof(asn_DEF_HeaderRecord_tags_1)
		/sizeof(asn_DEF_HeaderRecord_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_HeaderRecord_1,
	3,	/* Elements count */
	&asn_SPC_HeaderRecord_specs_1	/* Additional specs */
};

