/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "CDR"
 * 	found in "../cdr.asn1"
 * 	`asn1c -fskeletons-copy -fnative-types`
 */

#ifndef	_HeaderRecord_H_
#define	_HeaderRecord_H_


#include <asn_application.h>

/* Including external dependencies */
#include "TimeStamp.h"
#include "RecordingEntity.h"
#include "ManagementExtensions.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* HeaderRecord */
typedef struct HeaderRecord {
	TimeStamp_t	 productionDateTime;
	RecordingEntity_t	 recordingEntity;
	ManagementExtensions_t	 extensions;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} HeaderRecord_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_HeaderRecord;

#ifdef __cplusplus
}
#endif

#endif	/* _HeaderRecord_H_ */
#include <asn_internal.h>
