/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "CDR"
 * 	found in "../cdr.asn1"
 * 	`asn1c -fskeletons-copy -fnative-types`
 */

#ifndef	_HLRIntResult_H_
#define	_HLRIntResult_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Diagnostics.h"

#ifdef __cplusplus
extern "C" {
#endif

/* HLRIntResult */
typedef Diagnostics_t	 HLRIntResult_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_HLRIntResult;
asn_struct_free_f HLRIntResult_free;
asn_struct_print_f HLRIntResult_print;
asn_constr_check_f HLRIntResult_constraint;
ber_type_decoder_f HLRIntResult_decode_ber;
der_type_encoder_f HLRIntResult_encode_der;
xer_type_decoder_f HLRIntResult_decode_xer;
xer_type_encoder_f HLRIntResult_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _HLRIntResult_H_ */
#include <asn_internal.h>
