/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "CDR"
 * 	found in "../cdr.asn1"
 * 	`asn1c -fskeletons-copy -fnative-types`
 */

#ifndef	_IPBinaryAddress_H_
#define	_IPBinaryAddress_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum IPBinaryAddress_PR {
	IPBinaryAddress_PR_NOTHING,	/* No components present */
	IPBinaryAddress_PR_iPBinV4Address,
	IPBinaryAddress_PR_iPBinV6Address
} IPBinaryAddress_PR;

/* IPBinaryAddress */
typedef struct IPBinaryAddress {
	IPBinaryAddress_PR present;
	union IPBinaryAddress_u {
		OCTET_STRING_t	 iPBinV4Address;
		OCTET_STRING_t	 iPBinV6Address;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} IPBinaryAddress_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_IPBinaryAddress;

#ifdef __cplusplus
}
#endif

#endif	/* _IPBinaryAddress_H_ */
#include <asn_internal.h>
