/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "CDR"
 * 	found in "../cdr.asn1"
 * 	`asn1c -fskeletons-copy -fnative-types`
 */

#ifndef	_ISDNAddressString_H_
#define	_ISDNAddressString_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SCAddressString.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ISDNAddressString */
typedef SCAddressString_t	 ISDNAddressString_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ISDNAddressString;
asn_struct_free_f ISDNAddressString_free;
asn_struct_print_f ISDNAddressString_print;
asn_constr_check_f ISDNAddressString_constraint;
ber_type_decoder_f ISDNAddressString_decode_ber;
der_type_encoder_f ISDNAddressString_encode_der;
xer_type_decoder_f ISDNAddressString_decode_xer;
xer_type_encoder_f ISDNAddressString_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _ISDNAddressString_H_ */
#include <asn_internal.h>
