/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "CDR"
 * 	found in "../cdr.asn1"
 * 	`asn1c -fskeletons-copy -fnative-types`
 */

#ifndef	_LevelOfCAMELService_H_
#define	_LevelOfCAMELService_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LevelOfCAMELService {
	LevelOfCAMELService_basic	= 0,
	LevelOfCAMELService_callDurationSupervision	= 1,
	LevelOfCAMELService_onlineCharging	= 2
} e_LevelOfCAMELService;

/* LevelOfCAMELService */
typedef BIT_STRING_t	 LevelOfCAMELService_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LevelOfCAMELService;
asn_struct_free_f LevelOfCAMELService_free;
asn_struct_print_f LevelOfCAMELService_print;
asn_constr_check_f LevelOfCAMELService_constraint;
ber_type_decoder_f LevelOfCAMELService_decode_ber;
der_type_encoder_f LevelOfCAMELService_encode_der;
xer_type_decoder_f LevelOfCAMELService_decode_xer;
xer_type_encoder_f LevelOfCAMELService_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _LevelOfCAMELService_H_ */
#include <asn_internal.h>
