/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "CDR"
 * 	found in "../cdr.asn1"
 * 	`asn1c -fskeletons-copy -fnative-types`
 */

#ifndef	_LocationChange_H_
#define	_LocationChange_H_


#include <asn_application.h>

/* Including external dependencies */
#include "LocationAreaAndCell.h"
#include "TimeStamp.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* LocationChange */
typedef struct LocationChange {
	LocationAreaAndCell_t	 location;
	TimeStamp_t	 changeTime;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LocationChange_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LocationChange;

#ifdef __cplusplus
}
#endif

#endif	/* _LocationChange_H_ */
#include <asn_internal.h>
