/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "CDR"
 * 	found in "../cdr.asn1"
 * 	`asn1c -fskeletons-copy -fnative-types`
 */

#ifndef	_LocationAreaAndCell_H_
#define	_LocationAreaAndCell_H_


#include <asn_application.h>

/* Including external dependencies */
#include "LocationAreaCode.h"
#include "CellId.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* LocationAreaAndCell */
typedef struct LocationAreaAndCell {
	LocationAreaCode_t	 locationAreaCode;
	CellId_t	 cellIdentifier;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LocationAreaAndCell_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LocationAreaAndCell;

#ifdef __cplusplus
}
#endif

#endif	/* _LocationAreaAndCell_H_ */
#include <asn_internal.h>
