/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "CDR"
 * 	found in "../cdr.asn1"
 * 	`asn1c -fskeletons-copy -fnative-types`
 */

#ifndef	_LocUpdResult_H_
#define	_LocUpdResult_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Diagnostics.h"

#ifdef __cplusplus
extern "C" {
#endif

/* LocUpdResult */
typedef Diagnostics_t	 LocUpdResult_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LocUpdResult;
asn_struct_free_f LocUpdResult_free;
asn_struct_print_f LocUpdResult_print;
asn_constr_check_f LocUpdResult_constraint;
ber_type_decoder_f LocUpdResult_decode_ber;
der_type_encoder_f LocUpdResult_encode_der;
xer_type_decoder_f LocUpdResult_decode_xer;
xer_type_encoder_f LocUpdResult_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _LocUpdResult_H_ */
#include <asn_internal.h>
