/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "CDR"
 * 	found in "../cdr.asn1"
 * 	`asn1c -fskeletons-copy -fnative-types`
 */

#ifndef	_MCCMNC_H_
#define	_MCCMNC_H_


#include <asn_application.h>

/* Including external dependencies */
#include <GraphicString.h>

#ifdef __cplusplus
extern "C" {
#endif

/* MCCMNC */
typedef GraphicString_t	 MCCMNC_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MCCMNC;
asn_struct_free_f MCCMNC_free;
asn_struct_print_f MCCMNC_print;
asn_constr_check_f MCCMNC_constraint;
ber_type_decoder_f MCCMNC_decode_ber;
der_type_encoder_f MCCMNC_encode_der;
xer_type_decoder_f MCCMNC_decode_xer;
xer_type_encoder_f MCCMNC_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _MCCMNC_H_ */
#include <asn_internal.h>
