/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "CDR"
 * 	found in "../cdr.asn1"
 * 	`asn1c -fskeletons-copy -fnative-types`
 */

#ifndef	_MessageReference_H_
#define	_MessageReference_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* MessageReference */
typedef OCTET_STRING_t	 MessageReference_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MessageReference;
asn_struct_free_f MessageReference_free;
asn_struct_print_f MessageReference_print;
asn_constr_check_f MessageReference_constraint;
ber_type_decoder_f MessageReference_decode_ber;
der_type_encoder_f MessageReference_encode_der;
xer_type_decoder_f MessageReference_decode_xer;
xer_type_encoder_f MessageReference_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _MessageReference_H_ */
#include <asn_internal.h>
