/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "CDR"
 * 	found in "../cdr.asn1"
 * 	`asn1c -fskeletons-copy -fnative-types`
 */

#ifndef	_NetworkCallReference_H_
#define	_NetworkCallReference_H_


#include <asn_application.h>

/* Including external dependencies */
#include "CallReferenceNumber.h"

#ifdef __cplusplus
extern "C" {
#endif

/* NetworkCallReference */
typedef CallReferenceNumber_t	 NetworkCallReference_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NetworkCallReference;
asn_struct_free_f NetworkCallReference_free;
asn_struct_print_f NetworkCallReference_print;
asn_constr_check_f NetworkCallReference_constraint;
ber_type_decoder_f NetworkCallReference_decode_ber;
der_type_encoder_f NetworkCallReference_encode_der;
xer_type_decoder_f NetworkCallReference_decode_xer;
xer_type_encoder_f NetworkCallReference_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _NetworkCallReference_H_ */
#include <asn_internal.h>
