/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "CDR"
 * 	found in "../cdr.asn1"
 * 	`asn1c -fskeletons-copy -fnative-types`
 */

#ifndef	_NetworkSpecificCode_H_
#define	_NetworkSpecificCode_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* NetworkSpecificCode */
typedef long	 NetworkSpecificCode_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NetworkSpecificCode;
asn_struct_free_f NetworkSpecificCode_free;
asn_struct_print_f NetworkSpecificCode_print;
asn_constr_check_f NetworkSpecificCode_constraint;
ber_type_decoder_f NetworkSpecificCode_decode_ber;
der_type_encoder_f NetworkSpecificCode_encode_der;
xer_type_decoder_f NetworkSpecificCode_decode_xer;
xer_type_encoder_f NetworkSpecificCode_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _NetworkSpecificCode_H_ */
#include <asn_internal.h>
