/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "CDR"
 * 	found in "../cdr.asn1"
 * 	`asn1c -fskeletons-copy -fnative-types`
 */

#ifndef	_NetworkInitiatedPDPContext_H_
#define	_NetworkInitiatedPDPContext_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BOOLEAN.h>

#ifdef __cplusplus
extern "C" {
#endif

/* NetworkInitiatedPDPContext */
typedef BOOLEAN_t	 NetworkInitiatedPDPContext_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NetworkInitiatedPDPContext;
asn_struct_free_f NetworkInitiatedPDPContext_free;
asn_struct_print_f NetworkInitiatedPDPContext_print;
asn_constr_check_f NetworkInitiatedPDPContext_constraint;
ber_type_decoder_f NetworkInitiatedPDPContext_decode_ber;
der_type_encoder_f NetworkInitiatedPDPContext_encode_der;
xer_type_decoder_f NetworkInitiatedPDPContext_decode_xer;
xer_type_encoder_f NetworkInitiatedPDPContext_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _NetworkInitiatedPDPContext_H_ */
#include <asn_internal.h>
