/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "CDR"
 * 	found in "../cdr.asn1"
 * 	`asn1c -fskeletons-copy -fnative-types`
 */

#ifndef	_NumberOfDPEncountered_H_
#define	_NumberOfDPEncountered_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* NumberOfDPEncountered */
typedef long	 NumberOfDPEncountered_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NumberOfDPEncountered;
asn_struct_free_f NumberOfDPEncountered_free;
asn_struct_print_f NumberOfDPEncountered_print;
asn_constr_check_f NumberOfDPEncountered_constraint;
ber_type_decoder_f NumberOfDPEncountered_decode_ber;
der_type_encoder_f NumberOfDPEncountered_encode_der;
xer_type_decoder_f NumberOfDPEncountered_decode_xer;
xer_type_encoder_f NumberOfDPEncountered_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _NumberOfDPEncountered_H_ */
#include <asn_internal.h>
