/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "CDR"
 * 	found in "../cdr.asn1"
 * 	`asn1c -fskeletons-copy -fnative-types`
 */

#ifndef	_NumOfHSCSDChanRequested_H_
#define	_NumOfHSCSDChanRequested_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* NumOfHSCSDChanRequested */
typedef long	 NumOfHSCSDChanRequested_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NumOfHSCSDChanRequested;
asn_struct_free_f NumOfHSCSDChanRequested_free;
asn_struct_print_f NumOfHSCSDChanRequested_print;
asn_constr_check_f NumOfHSCSDChanRequested_constraint;
ber_type_decoder_f NumOfHSCSDChanRequested_decode_ber;
der_type_encoder_f NumOfHSCSDChanRequested_encode_der;
xer_type_decoder_f NumOfHSCSDChanRequested_decode_xer;
xer_type_encoder_f NumOfHSCSDChanRequested_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _NumOfHSCSDChanRequested_H_ */
#include <asn_internal.h>
