/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "CDR"
 * 	found in "../cdr.asn1"
 * 	`asn1c -fskeletons-copy -fnative-types`
 */

#ifndef	_QoSDelay_H_
#define	_QoSDelay_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum QoSDelay {
	QoSDelay_delayClass1	= 1,
	QoSDelay_delayClass2	= 2,
	QoSDelay_delayClass3	= 3,
	QoSDelay_delayClass4	= 4
} e_QoSDelay;

/* QoSDelay */
typedef long	 QoSDelay_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_QoSDelay;
asn_struct_free_f QoSDelay_free;
asn_struct_print_f QoSDelay_print;
asn_constr_check_f QoSDelay_constraint;
ber_type_decoder_f QoSDelay_decode_ber;
der_type_encoder_f QoSDelay_encode_der;
xer_type_decoder_f QoSDelay_decode_xer;
xer_type_encoder_f QoSDelay_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _QoSDelay_H_ */
#include <asn_internal.h>
