/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "CDR"
 * 	found in "../cdr.asn1"
 * 	`asn1c -fskeletons-copy -fnative-types`
 */

#include "QoSInformation.h"

static asn_TYPE_member_t asn_MBR_QoSInformation_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct QoSInformation, choice.gsmQosInformation),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_GSMQoSInformation,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"gsmQosInformation"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct QoSInformation, choice.umtsQosInformation),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ANY,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"umtsQosInformation"
		},
};
static asn_TYPE_tag2member_t asn_MAP_QoSInformation_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* gsmQosInformation at 670 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* umtsQosInformation at 673 */
};
static asn_CHOICE_specifics_t asn_SPC_QoSInformation_specs_1 = {
	sizeof(struct QoSInformation),
	offsetof(struct QoSInformation, _asn_ctx),
	offsetof(struct QoSInformation, present),
	sizeof(((struct QoSInformation *)0)->present),
	asn_MAP_QoSInformation_tag2el_1,
	2,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_QoSInformation = {
	"QoSInformation",
	"QoSInformation",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_QoSInformation_1,
	2,	/* Elements count */
	&asn_SPC_QoSInformation_specs_1	/* Additional specs */
};

