/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "CDR"
 * 	found in "../cdr.asn1"
 * 	`asn1c -fskeletons-copy -fnative-types`
 */

#ifndef	_QoSInformation_H_
#define	_QoSInformation_H_


#include <asn_application.h>

/* Including external dependencies */
#include "GSMQoSInformation.h"
#include <ANY.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum QoSInformation_PR {
	QoSInformation_PR_NOTHING,	/* No components present */
	QoSInformation_PR_gsmQosInformation,
	QoSInformation_PR_umtsQosInformation
} QoSInformation_PR;

/* QoSInformation */
typedef struct QoSInformation {
	QoSInformation_PR present;
	union QoSInformation_u {
		GSMQoSInformation_t	 gsmQosInformation;
		ANY_t	 umtsQosInformation;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} QoSInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_QoSInformation;

#ifdef __cplusplus
}
#endif

#endif	/* _QoSInformation_H_ */
#include <asn_internal.h>
