/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "CDR"
 * 	found in "../cdr.asn1"
 * 	`asn1c -fskeletons-copy -fnative-types`
 */

#include "QoSMeanThroughput.h"

int
QoSMeanThroughput_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	/* Replace with underlying type checker */
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static void
QoSMeanThroughput_1_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_NativeEnumerated.free_struct;
	td->print_struct   = asn_DEF_NativeEnumerated.print_struct;
	td->ber_decoder    = asn_DEF_NativeEnumerated.ber_decoder;
	td->der_encoder    = asn_DEF_NativeEnumerated.der_encoder;
	td->xer_decoder    = asn_DEF_NativeEnumerated.xer_decoder;
	td->xer_encoder    = asn_DEF_NativeEnumerated.xer_encoder;
	td->uper_decoder   = asn_DEF_NativeEnumerated.uper_decoder;
	td->uper_encoder   = asn_DEF_NativeEnumerated.uper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_NativeEnumerated.per_constraints;
	td->elements       = asn_DEF_NativeEnumerated.elements;
	td->elements_count = asn_DEF_NativeEnumerated.elements_count;
     /* td->specifics      = asn_DEF_NativeEnumerated.specifics;	// Defined explicitly */
}

void
QoSMeanThroughput_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, int contents_only) {
	QoSMeanThroughput_1_inherit_TYPE_descriptor(td);
	td->free_struct(td, struct_ptr, contents_only);
}

int
QoSMeanThroughput_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	QoSMeanThroughput_1_inherit_TYPE_descriptor(td);
	return td->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

asn_dec_rval_t
QoSMeanThroughput_decode_ber(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	QoSMeanThroughput_1_inherit_TYPE_descriptor(td);
	return td->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

asn_enc_rval_t
QoSMeanThroughput_encode_der(asn_TYPE_descriptor_t *td,
		void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	QoSMeanThroughput_1_inherit_TYPE_descriptor(td);
	return td->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

asn_dec_rval_t
QoSMeanThroughput_decode_xer(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	QoSMeanThroughput_1_inherit_TYPE_descriptor(td);
	return td->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

asn_enc_rval_t
QoSMeanThroughput_encode_xer(asn_TYPE_descriptor_t *td, void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	QoSMeanThroughput_1_inherit_TYPE_descriptor(td);
	return td->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

static asn_INTEGER_enum_map_t asn_MAP_QoSMeanThroughput_value2enum_1[] = {
	{ 0,	24,	"subscribedMeanThroughput" },
	{ 1,	14,	"mean100octetPh" },
	{ 2,	14,	"mean200octetPh" },
	{ 3,	14,	"mean500octetPh" },
	{ 4,	15,	"mean1000octetPh" },
	{ 5,	15,	"mean2000octetPh" },
	{ 6,	15,	"mean5000octetPh" },
	{ 7,	16,	"mean10000octetPh" },
	{ 8,	16,	"mean20000octetPh" },
	{ 9,	16,	"mean50000octetPh" },
	{ 10,	17,	"mean100000octetPh" },
	{ 11,	17,	"mean200000octetPh" },
	{ 12,	17,	"mean500000octetPh" },
	{ 13,	18,	"mean1000000octetPh" },
	{ 14,	18,	"mean2000000octetPh" },
	{ 15,	18,	"mean5000000octetPh" },
	{ 16,	19,	"mean10000000octetPh" },
	{ 17,	19,	"mean20000000octetPh" },
	{ 18,	19,	"mean50000000octetPh" },
	{ 30,	8,	"reserved" },
	{ 31,	10,	"bestEffort" }
};
static unsigned int asn_MAP_QoSMeanThroughput_enum2value_1[] = {
	20,	/* bestEffort(31) */
	16,	/* mean10000000octetPh(16) */
	13,	/* mean1000000octetPh(13) */
	10,	/* mean100000octetPh(10) */
	7,	/* mean10000octetPh(7) */
	4,	/* mean1000octetPh(4) */
	1,	/* mean100octetPh(1) */
	17,	/* mean20000000octetPh(17) */
	14,	/* mean2000000octetPh(14) */
	11,	/* mean200000octetPh(11) */
	8,	/* mean20000octetPh(8) */
	5,	/* mean2000octetPh(5) */
	2,	/* mean200octetPh(2) */
	18,	/* mean50000000octetPh(18) */
	15,	/* mean5000000octetPh(15) */
	12,	/* mean500000octetPh(12) */
	9,	/* mean50000octetPh(9) */
	6,	/* mean5000octetPh(6) */
	3,	/* mean500octetPh(3) */
	19,	/* reserved(30) */
	0	/* subscribedMeanThroughput(0) */
};
static asn_INTEGER_specifics_t asn_SPC_QoSMeanThroughput_specs_1 = {
	asn_MAP_QoSMeanThroughput_value2enum_1,	/* "tag" => N; sorted by tag */
	asn_MAP_QoSMeanThroughput_enum2value_1,	/* N => "tag"; sorted by N */
	21,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static ber_tlv_tag_t asn_DEF_QoSMeanThroughput_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
asn_TYPE_descriptor_t asn_DEF_QoSMeanThroughput = {
	"QoSMeanThroughput",
	"QoSMeanThroughput",
	QoSMeanThroughput_free,
	QoSMeanThroughput_print,
	QoSMeanThroughput_constraint,
	QoSMeanThroughput_decode_ber,
	QoSMeanThroughput_encode_der,
	QoSMeanThroughput_decode_xer,
	QoSMeanThroughput_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_QoSMeanThroughput_tags_1,
	sizeof(asn_DEF_QoSMeanThroughput_tags_1)
		/sizeof(asn_DEF_QoSMeanThroughput_tags_1[0]), /* 1 */
	asn_DEF_QoSMeanThroughput_tags_1,	/* Same as above */
	sizeof(asn_DEF_QoSMeanThroughput_tags_1)
		/sizeof(asn_DEF_QoSMeanThroughput_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	0, 0,	/* Defined elsewhere */
	&asn_SPC_QoSMeanThroughput_specs_1	/* Additional specs */
};

