/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "CDR"
 * 	found in "../cdr.asn1"
 * 	`asn1c -fskeletons-copy -fnative-types`
 */

#ifndef	_QoSMeanThroughput_H_
#define	_QoSMeanThroughput_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum QoSMeanThroughput {
	QoSMeanThroughput_subscribedMeanThroughput	= 0,
	QoSMeanThroughput_mean100octetPh	= 1,
	QoSMeanThroughput_mean200octetPh	= 2,
	QoSMeanThroughput_mean500octetPh	= 3,
	QoSMeanThroughput_mean1000octetPh	= 4,
	QoSMeanThroughput_mean2000octetPh	= 5,
	QoSMeanThroughput_mean5000octetPh	= 6,
	QoSMeanThroughput_mean10000octetPh	= 7,
	QoSMeanThroughput_mean20000octetPh	= 8,
	QoSMeanThroughput_mean50000octetPh	= 9,
	QoSMeanThroughput_mean100000octetPh	= 10,
	QoSMeanThroughput_mean200000octetPh	= 11,
	QoSMeanThroughput_mean500000octetPh	= 12,
	QoSMeanThroughput_mean1000000octetPh	= 13,
	QoSMeanThroughput_mean2000000octetPh	= 14,
	QoSMeanThroughput_mean5000000octetPh	= 15,
	QoSMeanThroughput_mean10000000octetPh	= 16,
	QoSMeanThroughput_mean20000000octetPh	= 17,
	QoSMeanThroughput_mean50000000octetPh	= 18,
	QoSMeanThroughput_reserved	= 30,
	QoSMeanThroughput_bestEffort	= 31
} e_QoSMeanThroughput;

/* QoSMeanThroughput */
typedef long	 QoSMeanThroughput_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_QoSMeanThroughput;
asn_struct_free_f QoSMeanThroughput_free;
asn_struct_print_f QoSMeanThroughput_print;
asn_constr_check_f QoSMeanThroughput_constraint;
ber_type_decoder_f QoSMeanThroughput_decode_ber;
der_type_encoder_f QoSMeanThroughput_encode_der;
xer_type_decoder_f QoSMeanThroughput_decode_xer;
xer_type_encoder_f QoSMeanThroughput_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _QoSMeanThroughput_H_ */
#include <asn_internal.h>
