/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "CDR"
 * 	found in "../cdr.asn1"
 * 	`asn1c -fskeletons-copy -fnative-types`
 */

#ifndef	_QoSPeakThroughput_H_
#define	_QoSPeakThroughput_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum QoSPeakThroughput {
	QoSPeakThroughput_unspecified	= 0,
	QoSPeakThroughput_upTo1000octetPs	= 1,
	QoSPeakThroughput_upTo2000octetPs	= 2,
	QoSPeakThroughput_upTo4000octetPs	= 3,
	QoSPeakThroughput_upTo8000octetPs	= 4,
	QoSPeakThroughput_upTo16000octetPs	= 5,
	QoSPeakThroughput_upTo32000octetPs	= 6,
	QoSPeakThroughput_upTo64000octetPs	= 7,
	QoSPeakThroughput_upTo128000octetPs	= 8,
	QoSPeakThroughput_upTo256000octetPs	= 9
} e_QoSPeakThroughput;

/* QoSPeakThroughput */
typedef long	 QoSPeakThroughput_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_QoSPeakThroughput;
asn_struct_free_f QoSPeakThroughput_free;
asn_struct_print_f QoSPeakThroughput_print;
asn_constr_check_f QoSPeakThroughput_constraint;
ber_type_decoder_f QoSPeakThroughput_decode_ber;
der_type_encoder_f QoSPeakThroughput_encode_der;
xer_type_decoder_f QoSPeakThroughput_decode_xer;
xer_type_encoder_f QoSPeakThroughput_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _QoSPeakThroughput_H_ */
#include <asn_internal.h>
