/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "CDR"
 * 	found in "../cdr.asn1"
 * 	`asn1c -fskeletons-copy -fnative-types`
 */

#ifndef	_QoSReliability_H_
#define	_QoSReliability_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum QoSReliability {
	QoSReliability_unspecifiedReliability	= 0,
	QoSReliability_acknowledgedGTP	= 1,
	QoSReliability_unackGTPAcknowLLC	= 2,
	QoSReliability_unackGTPLLCAcknowRLC	= 3,
	QoSReliability_unackGTPLLCRLC	= 4,
	QoSReliability_unacknowUnprotectedData	= 5
} e_QoSReliability;

/* QoSReliability */
typedef long	 QoSReliability_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_QoSReliability;
asn_struct_free_f QoSReliability_free;
asn_struct_print_f QoSReliability_print;
asn_constr_check_f QoSReliability_constraint;
ber_type_decoder_f QoSReliability_decode_ber;
der_type_encoder_f QoSReliability_encode_der;
xer_type_decoder_f QoSReliability_decode_xer;
xer_type_encoder_f QoSReliability_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _QoSReliability_H_ */
#include <asn_internal.h>
