/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "CDR"
 * 	found in "../cdr.asn1"
 * 	`asn1c -fskeletons-copy -fnative-types`
 */

#ifndef	_RadioChannelsRequested_H_
#define	_RadioChannelsRequested_H_


#include <asn_application.h>

/* Including external dependencies */
#include "RadioChanRequested.h"
#include <asn_SET_OF.h>
#include <constr_SET_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RadioChannelsRequested */
typedef struct RadioChannelsRequested {
	A_SET_OF(RadioChanRequested_t) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RadioChannelsRequested_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RadioChannelsRequested;

#ifdef __cplusplus
}
#endif

#endif	/* _RadioChannelsRequested_H_ */
#include <asn_internal.h>
