/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "CDR"
 * 	found in "../cdr.asn1"
 * 	`asn1c -fskeletons-copy -fnative-types`
 */

#ifndef	_RadioChanRequested_H_
#define	_RadioChanRequested_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RadioChanRequested {
	RadioChanRequested_halfRateChannel	= 0,
	RadioChanRequested_fullRateChannel	= 1,
	RadioChanRequested_dualHalfRatePreferred	= 2,
	RadioChanRequested_dualFullRatePreferred	= 3
} e_RadioChanRequested;

/* RadioChanRequested */
typedef long	 RadioChanRequested_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RadioChanRequested;
asn_struct_free_f RadioChanRequested_free;
asn_struct_print_f RadioChanRequested_print;
asn_constr_check_f RadioChanRequested_constraint;
ber_type_decoder_f RadioChanRequested_decode_ber;
der_type_encoder_f RadioChanRequested_encode_der;
xer_type_decoder_f RadioChanRequested_decode_xer;
xer_type_encoder_f RadioChanRequested_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _RadioChanRequested_H_ */
#include <asn_internal.h>
