/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "CDR"
 * 	found in "../cdr.asn1"
 * 	`asn1c -fskeletons-copy -fnative-types`
 */

#ifndef	_RedirectingNumber_H_
#define	_RedirectingNumber_H_


#include <asn_application.h>

/* Including external dependencies */
#include "BCDDirectoryNumber.h"

#ifdef __cplusplus
extern "C" {
#endif

/* RedirectingNumber */
typedef BCDDirectoryNumber_t	 RedirectingNumber_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RedirectingNumber;
asn_struct_free_f RedirectingNumber_free;
asn_struct_print_f RedirectingNumber_print;
asn_constr_check_f RedirectingNumber_constraint;
ber_type_decoder_f RedirectingNumber_decode_ber;
der_type_encoder_f RedirectingNumber_encode_der;
xer_type_decoder_f RedirectingNumber_decode_xer;
xer_type_encoder_f RedirectingNumber_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _RedirectingNumber_H_ */
#include <asn_internal.h>
