/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "CDR"
 * 	found in "../cdr.asn1"
 * 	`asn1c -fskeletons-copy -fnative-types`
 */

#ifndef	_RoamingNumber_H_
#define	_RoamingNumber_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ISDN-AddressString.h"

#ifdef __cplusplus
extern "C" {
#endif

/* RoamingNumber */
typedef ISDN_AddressString_t	 RoamingNumber_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RoamingNumber;
asn_struct_free_f RoamingNumber_free;
asn_struct_print_f RoamingNumber_print;
asn_constr_check_f RoamingNumber_constraint;
ber_type_decoder_f RoamingNumber_decode_ber;
der_type_encoder_f RoamingNumber_encode_der;
xer_type_decoder_f RoamingNumber_decode_xer;
xer_type_encoder_f RoamingNumber_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _RoamingNumber_H_ */
#include <asn_internal.h>
