/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "CDR"
 * 	found in "../cdr.asn1"
 * 	`asn1c -fskeletons-copy -fnative-types`
 */

#include "RoutingNumber.h"

static asn_TYPE_member_t asn_MBR_RoutingNumber_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RoutingNumber, choice.roaming),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RoamingNumber,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"roaming"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RoutingNumber, choice.forwarded),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ForwardToNumber,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"forwarded"
		},
};
static asn_TYPE_tag2member_t asn_MAP_RoutingNumber_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 0, 0, 0 }, /* roaming at 580 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 1, 0, 0 } /* forwarded at 582 */
};
static asn_CHOICE_specifics_t asn_SPC_RoutingNumber_specs_1 = {
	sizeof(struct RoutingNumber),
	offsetof(struct RoutingNumber, _asn_ctx),
	offsetof(struct RoutingNumber, present),
	sizeof(((struct RoutingNumber *)0)->present),
	asn_MAP_RoutingNumber_tag2el_1,
	2,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_RoutingNumber = {
	"RoutingNumber",
	"RoutingNumber",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_RoutingNumber_1,
	2,	/* Elements count */
	&asn_SPC_RoutingNumber_specs_1	/* Additional specs */
};

