/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "CDR"
 * 	found in "../cdr.asn1"
 * 	`asn1c -fskeletons-copy -fnative-types`
 */

#ifndef	_SCFAddress_H_
#define	_SCFAddress_H_


#include <asn_application.h>

/* Including external dependencies */
#include "AddressString.h"

#ifdef __cplusplus
extern "C" {
#endif

/* SCFAddress */
typedef AddressString_t	 SCFAddress_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SCFAddress;
asn_struct_free_f SCFAddress_free;
asn_struct_print_f SCFAddress_print;
asn_constr_check_f SCFAddress_constraint;
ber_type_decoder_f SCFAddress_decode_ber;
der_type_encoder_f SCFAddress_encode_der;
xer_type_decoder_f SCFAddress_decode_xer;
xer_type_encoder_f SCFAddress_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _SCFAddress_H_ */
#include <asn_internal.h>
