/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "CDR"
 * 	found in "../cdr.asn1"
 * 	`asn1c -fskeletons-copy -fnative-types`
 */

#ifndef	_ServiceDistanceDependency_H_
#define	_ServiceDistanceDependency_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ServiceDistanceDependency */
typedef struct ServiceDistanceDependency {
	long	 aocService;
	long	*chargingZone	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ServiceDistanceDependency_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ServiceDistanceDependency;

#ifdef __cplusplus
}
#endif

#endif	/* _ServiceDistanceDependency_H_ */
#include <asn_internal.h>
