/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "CDR"
 * 	found in "../cdr.asn1"
 * 	`asn1c -fskeletons-copy -fnative-types`
 */

#ifndef	_ServiceDistanceDependencies_H_
#define	_ServiceDistanceDependencies_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SET_OF.h>
#include <constr_SET_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ServiceDistanceDependency;

/* ServiceDistanceDependencies */
typedef struct ServiceDistanceDependencies {
	A_SET_OF(struct ServiceDistanceDependency) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ServiceDistanceDependencies_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ServiceDistanceDependencies;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ServiceDistanceDependency.h"

#endif	/* _ServiceDistanceDependencies_H_ */
#include <asn_internal.h>
