/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "CDR"
 * 	found in "../cdr.asn1"
 * 	`asn1c -fskeletons-copy -fnative-types`
 */

#ifndef	_SGSNSMORecord_H_
#define	_SGSNSMORecord_H_


#include <asn_application.h>

/* Including external dependencies */
#include "CallEventRecordType.h"
#include "IMSI.h"
#include "IMEI.h"
#include "MSISDN.h"
#include "MSNetworkCapability.h"
#include "AddressString.h"
#include "RecordingEntity.h"
#include "LocationAreaCode.h"
#include "RoutingAreaCode.h"
#include "CellId.h"
#include "MessageReference.h"
#include "TimeStamp.h"
#include "NodeID.h"
#include "LocalSequenceNumber.h"
#include "ChargingCharacteristics.h"
#include "SystemType.h"
#include "CalledNumber.h"
#include <constr_SET.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */

/*
 * Method of determining the components presence
 */
typedef enum SGSNSMORecord_PR {
	SGSNSMORecord_PR_recordType,	/* Member recordType is present */
	SGSNSMORecord_PR_servedIMSI,	/* Member servedIMSI is present */
	SGSNSMORecord_PR_servedIMEI,	/* Member servedIMEI is present */
	SGSNSMORecord_PR_servedMSISDN,	/* Member servedMSISDN is present */
	SGSNSMORecord_PR_msNetworkCapability,	/* Member msNetworkCapability is present */
	SGSNSMORecord_PR_serviceCentre,	/* Member serviceCentre is present */
	SGSNSMORecord_PR_recordingEntity,	/* Member recordingEntity is present */
	SGSNSMORecord_PR_locationArea,	/* Member locationArea is present */
	SGSNSMORecord_PR_routingArea,	/* Member routingArea is present */
	SGSNSMORecord_PR_cellIdentifier,	/* Member cellIdentifier is present */
	SGSNSMORecord_PR_messageReference,	/* Member messageReference is present */
	SGSNSMORecord_PR_originationTime,	/* Member originationTime is present */
	SGSNSMORecord_PR_smsResult,	/* Member smsResult is present */
	SGSNSMORecord_PR_recordExtensions,	/* Member recordExtensions is present */
	SGSNSMORecord_PR_nodeID,	/* Member nodeID is present */
	SGSNSMORecord_PR_localSequenceNumber,	/* Member localSequenceNumber is present */
	SGSNSMORecord_PR_chargingCharacteristics,	/* Member chargingCharacteristics is present */
	SGSNSMORecord_PR_systemType,	/* Member systemType is present */
	SGSNSMORecord_PR_destinationNumber,	/* Member destinationNumber is present */
	SGSNSMORecord_PR_cAMELInformationSMS,	/* Member cAMELInformationSMS is present */
} SGSNSMORecord_PR;

/* Forward declarations */
struct Diagnostics;
struct ManagementExtensions;
struct CAMELInformationSMS;

/* SGSNSMORecord */
typedef struct SGSNSMORecord {
	CallEventRecordType_t	 recordType;
	IMSI_t	 servedIMSI;
	IMEI_t	*servedIMEI	/* OPTIONAL */;
	MSISDN_t	*servedMSISDN	/* OPTIONAL */;
	MSNetworkCapability_t	 msNetworkCapability;
	AddressString_t	 serviceCentre;
	RecordingEntity_t	 recordingEntity;
	LocationAreaCode_t	*locationArea	/* OPTIONAL */;
	RoutingAreaCode_t	*routingArea	/* OPTIONAL */;
	CellId_t	*cellIdentifier	/* OPTIONAL */;
	MessageReference_t	 messageReference;
	TimeStamp_t	 originationTime;
	struct Diagnostics	*smsResult	/* OPTIONAL */;
	struct ManagementExtensions	*recordExtensions	/* OPTIONAL */;
	NodeID_t	*nodeID	/* OPTIONAL */;
	LocalSequenceNumber_t	*localSequenceNumber	/* OPTIONAL */;
	ChargingCharacteristics_t	*chargingCharacteristics	/* OPTIONAL */;
	SystemType_t	*systemType	/* OPTIONAL */;
	CalledNumber_t	*destinationNumber	/* OPTIONAL */;
	struct CAMELInformationSMS	*cAMELInformationSMS	/* OPTIONAL */;
	
	/* Presence bitmask: ASN_SET_ISPRESENT(pSGSNSMORecord, SGSNSMORecord_PR_x) */
	unsigned int _presence_map
		[((20+(8*sizeof(unsigned int))-1)/(8*sizeof(unsigned int)))];
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SGSNSMORecord_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SGSNSMORecord;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "SMSResult.h"
#include "ManagementExtensions.h"
#include "CAMELInformationSMS.h"

#endif	/* _SGSNSMORecord_H_ */
#include <asn_internal.h>
