/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "CDR"
 * 	found in "../cdr.asn1"
 * 	`asn1c -fskeletons-copy -fnative-types`
 */

#ifndef	_SGSNMMRecord_H_
#define	_SGSNMMRecord_H_


#include <asn_application.h>

/* Including external dependencies */
#include "CallEventRecordType.h"
#include "IMSI.h"
#include "IMEI.h"
#include "GSNAddress.h"
#include "MSNetworkCapability.h"
#include "RoutingAreaCode.h"
#include "LocationAreaCode.h"
#include "CellId.h"
#include "TimeStamp.h"
#include "CallDuration.h"
#include "SGSNChange.h"
#include "CauseForRecClosing.h"
#include <NativeInteger.h>
#include "NodeID.h"
#include "LocalSequenceNumber.h"
#include "MSISDN.h"
#include "ChargingCharacteristics.h"
#include "SystemType.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SET.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */

/*
 * Method of determining the components presence
 */
typedef enum SGSNMMRecord_PR {
	SGSNMMRecord_PR_recordType,	/* Member recordType is present */
	SGSNMMRecord_PR_servedIMSI,	/* Member servedIMSI is present */
	SGSNMMRecord_PR_servedIMEI,	/* Member servedIMEI is present */
	SGSNMMRecord_PR_sgsnAddress,	/* Member sgsnAddress is present */
	SGSNMMRecord_PR_msNetworkCapability,	/* Member msNetworkCapability is present */
	SGSNMMRecord_PR_routingArea,	/* Member routingArea is present */
	SGSNMMRecord_PR_locationAreaCode,	/* Member locationAreaCode is present */
	SGSNMMRecord_PR_cellIdentifier,	/* Member cellIdentifier is present */
	SGSNMMRecord_PR_changeLocation,	/* Member changeLocation is present */
	SGSNMMRecord_PR_recordOpeningTime,	/* Member recordOpeningTime is present */
	SGSNMMRecord_PR_duration,	/* Member duration is present */
	SGSNMMRecord_PR_sgsnChange,	/* Member sgsnChange is present */
	SGSNMMRecord_PR_causeForRecClosing,	/* Member causeForRecClosing is present */
	SGSNMMRecord_PR_diagnostics,	/* Member diagnostics is present */
	SGSNMMRecord_PR_recordSequenceNumber,	/* Member recordSequenceNumber is present */
	SGSNMMRecord_PR_nodeID,	/* Member nodeID is present */
	SGSNMMRecord_PR_recordExtensions,	/* Member recordExtensions is present */
	SGSNMMRecord_PR_localSequenceNumber,	/* Member localSequenceNumber is present */
	SGSNMMRecord_PR_servedMSISDN,	/* Member servedMSISDN is present */
	SGSNMMRecord_PR_chargingCharacteristics,	/* Member chargingCharacteristics is present */
	SGSNMMRecord_PR_cAMELInformationMM,	/* Member cAMELInformationMM is present */
	SGSNMMRecord_PR_systemType,	/* Member systemType is present */
} SGSNMMRecord_PR;

/* Forward declarations */
struct Diagnostics;
struct ManagementExtensions;
struct CAMELInformationMM;
struct ChangeLocation;

/* SGSNMMRecord */
typedef struct SGSNMMRecord {
	CallEventRecordType_t	 recordType;
	IMSI_t	 servedIMSI;
	IMEI_t	*servedIMEI	/* OPTIONAL */;
	GSNAddress_t	 sgsnAddress;
	MSNetworkCapability_t	*msNetworkCapability	/* OPTIONAL */;
	RoutingAreaCode_t	*routingArea	/* OPTIONAL */;
	LocationAreaCode_t	*locationAreaCode	/* OPTIONAL */;
	CellId_t	*cellIdentifier	/* OPTIONAL */;
	struct SGSNMMRecord__changeLocation {
		A_SEQUENCE_OF(struct ChangeLocation) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *changeLocation;
	TimeStamp_t	 recordOpeningTime;
	CallDuration_t	*duration	/* OPTIONAL */;
	SGSNChange_t	*sgsnChange	/* OPTIONAL */;
	CauseForRecClosing_t	 causeForRecClosing;
	struct Diagnostics	*diagnostics	/* OPTIONAL */;
	long	*recordSequenceNumber	/* OPTIONAL */;
	NodeID_t	*nodeID	/* OPTIONAL */;
	struct ManagementExtensions	*recordExtensions	/* OPTIONAL */;
	LocalSequenceNumber_t	*localSequenceNumber	/* OPTIONAL */;
	MSISDN_t	*servedMSISDN	/* OPTIONAL */;
	ChargingCharacteristics_t	*chargingCharacteristics	/* OPTIONAL */;
	struct CAMELInformationMM	*cAMELInformationMM	/* OPTIONAL */;
	SystemType_t	*systemType	/* OPTIONAL */;
	
	/* Presence bitmask: ASN_SET_ISPRESENT(pSGSNMMRecord, SGSNMMRecord_PR_x) */
	unsigned int _presence_map
		[((22+(8*sizeof(unsigned int))-1)/(8*sizeof(unsigned int)))];
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SGSNMMRecord_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SGSNMMRecord;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Diagnostics.h"
#include "ManagementExtensions.h"
#include "CAMELInformationMM.h"
#include "ChangeLocation.h"

#endif	/* _SGSNMMRecord_H_ */
#include <asn_internal.h>
