/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "CDR"
 * 	found in "../cdr.asn1"
 * 	`asn1c -fskeletons-copy -fnative-types`
 */

#ifndef	_SimpleStringName_H_
#define	_SimpleStringName_H_


#include <asn_application.h>

/* Including external dependencies */
#include <GraphicString.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SimpleStringName */
typedef GraphicString_t	 SimpleStringName_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SimpleStringName;
asn_struct_free_f SimpleStringName_free;
asn_struct_print_f SimpleStringName_print;
asn_constr_check_f SimpleStringName_constraint;
ber_type_decoder_f SimpleStringName_decode_ber;
der_type_encoder_f SimpleStringName_encode_der;
xer_type_decoder_f SimpleStringName_decode_xer;
xer_type_encoder_f SimpleStringName_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _SimpleStringName_H_ */
#include <asn_internal.h>
