/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "CDR"
 * 	found in "../cdr.asn1"
 * 	`asn1c -fskeletons-copy -fnative-types`
 */

#ifndef	_SimpleIntegerName_H_
#define	_SimpleIntegerName_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SimpleIntegerName */
typedef long	 SimpleIntegerName_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SimpleIntegerName;
asn_struct_free_f SimpleIntegerName_free;
asn_struct_print_f SimpleIntegerName_print;
asn_constr_check_f SimpleIntegerName_constraint;
ber_type_decoder_f SimpleIntegerName_decode_ber;
der_type_encoder_f SimpleIntegerName_encode_der;
xer_type_decoder_f SimpleIntegerName_decode_xer;
xer_type_encoder_f SimpleIntegerName_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _SimpleIntegerName_H_ */
#include <asn_internal.h>
