/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "CDR"
 * 	found in "../cdr.asn1"
 * 	`asn1c -fskeletons-copy -fnative-types`
 */

#ifndef	_SMSResult_H_
#define	_SMSResult_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Diagnostics.h"

#ifdef __cplusplus
extern "C" {
#endif

/* SMSResult */
typedef Diagnostics_t	 SMSResult_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SMSResult;
asn_struct_free_f SMSResult_free;
asn_struct_print_f SMSResult_print;
asn_constr_check_f SMSResult_constraint;
ber_type_decoder_f SMSResult_decode_ber;
der_type_encoder_f SMSResult_encode_der;
xer_type_decoder_f SMSResult_decode_xer;
xer_type_encoder_f SMSResult_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _SMSResult_H_ */
#include <asn_internal.h>
