/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "CDR"
 * 	found in "../cdr.asn1"
 * 	`asn1c -fskeletons-copy -fnative-types`
 */

#ifndef	_SpeechVersionIdentifier_H_
#define	_SpeechVersionIdentifier_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SpeechVersionIdentifier */
typedef OCTET_STRING_t	 SpeechVersionIdentifier_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SpeechVersionIdentifier;
asn_struct_free_f SpeechVersionIdentifier_free;
asn_struct_print_f SpeechVersionIdentifier_print;
asn_constr_check_f SpeechVersionIdentifier_constraint;
ber_type_decoder_f SpeechVersionIdentifier_decode_ber;
der_type_encoder_f SpeechVersionIdentifier_encode_der;
xer_type_decoder_f SpeechVersionIdentifier_decode_xer;
xer_type_encoder_f SpeechVersionIdentifier_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _SpeechVersionIdentifier_H_ */
#include <asn_internal.h>
