/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "CDR"
 * 	found in "../cdr.asn1"
 * 	`asn1c -fskeletons-copy -fnative-types`
 */

#ifndef	_SSActionType_H_
#define	_SSActionType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SSActionType {
	SSActionType_registration	= 0,
	SSActionType_erasure	= 1,
	SSActionType_activation	= 2,
	SSActionType_deactivation	= 3,
	SSActionType_interrogation	= 4,
	SSActionType_invocation	= 5,
	SSActionType_passwordRegistration	= 6
} e_SSActionType;

/* SSActionType */
typedef long	 SSActionType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SSActionType;
asn_struct_free_f SSActionType_free;
asn_struct_print_f SSActionType_print;
asn_constr_check_f SSActionType_constraint;
ber_type_decoder_f SSActionType_decode_ber;
der_type_encoder_f SSActionType_encode_der;
xer_type_decoder_f SSActionType_decode_xer;
xer_type_encoder_f SSActionType_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _SSActionType_H_ */
#include <asn_internal.h>
