/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "CDR"
 * 	found in "../cdr.asn1"
 * 	`asn1c -fskeletons-copy -fnative-types`
 */

#ifndef	_SSParameters_H_
#define	_SSParameters_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ForwardToNumber.h"
#include <OCTET_STRING.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SSParameters_PR {
	SSParameters_PR_NOTHING,	/* No components present */
	SSParameters_PR_forwardedToNumber,
	SSParameters_PR_unstructuredData
} SSParameters_PR;

/* SSParameters */
typedef struct SSParameters {
	SSParameters_PR present;
	union SSParameters_u {
		ForwardToNumber_t	 forwardedToNumber;
		OCTET_STRING_t	 unstructuredData;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SSParameters_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SSParameters;

#ifdef __cplusplus
}
#endif

#endif	/* _SSParameters_H_ */
#include <asn_internal.h>
