/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "CDR"
 * 	found in "../cdr.asn1"
 * 	`asn1c -fskeletons-copy -fnative-types`
 */

#include "SSParameters.h"

static asn_TYPE_member_t asn_MBR_SSParameters_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SSParameters, choice.forwardedToNumber),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ForwardToNumber,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"forwardedToNumber"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SSParameters, choice.unstructuredData),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"unstructuredData"
		},
};
static asn_TYPE_tag2member_t asn_MAP_SSParameters_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* forwardedToNumber at 637 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* unstructuredData at 638 */
};
static asn_CHOICE_specifics_t asn_SPC_SSParameters_specs_1 = {
	sizeof(struct SSParameters),
	offsetof(struct SSParameters, _asn_ctx),
	offsetof(struct SSParameters, present),
	sizeof(((struct SSParameters *)0)->present),
	asn_MAP_SSParameters_tag2el_1,
	2,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_SSParameters = {
	"SSParameters",
	"SSParameters",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_SSParameters_1,
	2,	/* Elements count */
	&asn_SPC_SSParameters_specs_1	/* Additional specs */
};

