/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "CDR"
 * 	found in "../cdr.asn1"
 * 	`asn1c -fskeletons-copy -fnative-types`
 */

#ifndef	_SupplServices_H_
#define	_SupplServices_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SS-Code.h"
#include <asn_SET_OF.h>
#include <constr_SET_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SupplServices */
typedef struct SupplServices {
	A_SET_OF(SS_Code_t) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SupplServices_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SupplServices;

#ifdef __cplusplus
}
#endif

#endif	/* _SupplServices_H_ */
#include <asn_internal.h>
