/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "CDR"
 * 	found in "../cdr.asn1"
 * 	`asn1c -fskeletons-copy -fnative-types`
 */

#ifndef	_SuppServiceUsed_H_
#define	_SuppServiceUsed_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SS-Code.h"
#include "TimeStamp.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SuppServiceUsed */
typedef struct SuppServiceUsed {
	SS_Code_t	 ssCode;
	TimeStamp_t	*ssTime	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SuppServiceUsed_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SuppServiceUsed;

#ifdef __cplusplus
}
#endif

#endif	/* _SuppServiceUsed_H_ */
#include <asn_internal.h>
