/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "CDR"
 * 	found in "../cdr.asn1"
 * 	`asn1c -fskeletons-copy -fnative-types`
 */

#ifndef	_SystemType_H_
#define	_SystemType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SystemType {
	SystemType_unknown	= 0,
	SystemType_iuUTRAN	= 1,
	SystemType_gERAN	= 2
} e_SystemType;

/* SystemType */
typedef long	 SystemType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SystemType;
asn_struct_free_f SystemType_free;
asn_struct_print_f SystemType_print;
asn_constr_check_f SystemType_constraint;
ber_type_decoder_f SystemType_decode_ber;
der_type_encoder_f SystemType_encode_der;
xer_type_decoder_f SystemType_decode_xer;
xer_type_encoder_f SystemType_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _SystemType_H_ */
#include <asn_internal.h>
