/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "CDR"
 * 	found in "../cdr.asn1"
 * 	`asn1c -fskeletons-copy -fnative-types`
 */

#ifndef	_SystemType1_H_
#define	_SystemType1_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SystemType1 {
	SystemType1_unknown	= 0,
	SystemType1_iuUTRAN	= 1,
	SystemType1_gERAN	= 2
} e_SystemType1;

/* SystemType1 */
typedef long	 SystemType1_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SystemType1;
asn_struct_free_f SystemType1_free;
asn_struct_print_f SystemType1_print;
asn_constr_check_f SystemType1_constraint;
ber_type_decoder_f SystemType1_decode_ber;
der_type_encoder_f SystemType1_encode_der;
xer_type_decoder_f SystemType1_decode_xer;
xer_type_encoder_f SystemType1_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _SystemType1_H_ */
#include <asn_internal.h>
