/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "CDR"
 * 	found in "../cdr.asn1"
 * 	`asn1c -fskeletons-copy -fnative-types`
 */

#ifndef	_TranslatedNumber_H_
#define	_TranslatedNumber_H_


#include <asn_application.h>

/* Including external dependencies */
#include "BCDDirectoryNumber.h"

#ifdef __cplusplus
extern "C" {
#endif

/* TranslatedNumber */
typedef BCDDirectoryNumber_t	 TranslatedNumber_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TranslatedNumber;
asn_struct_free_f TranslatedNumber_free;
asn_struct_print_f TranslatedNumber_print;
asn_constr_check_f TranslatedNumber_constraint;
ber_type_decoder_f TranslatedNumber_decode_ber;
der_type_encoder_f TranslatedNumber_encode_der;
xer_type_decoder_f TranslatedNumber_decode_xer;
xer_type_encoder_f TranslatedNumber_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _TranslatedNumber_H_ */
#include <asn_internal.h>
