/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "CDR"
 * 	found in "../cdr.asn1"
 * 	`asn1c -fskeletons-copy -fnative-types`
 */

#ifndef	_TrunkGroup_H_
#define	_TrunkGroup_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <GraphicString.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TrunkGroup_PR {
	TrunkGroup_PR_NOTHING,	/* No components present */
	TrunkGroup_PR_tkgpNumber,
	TrunkGroup_PR_tkgpName
} TrunkGroup_PR;

/* TrunkGroup */
typedef struct TrunkGroup {
	TrunkGroup_PR present;
	union TrunkGroup_u {
		long	 tkgpNumber;
		GraphicString_t	 tkgpName;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TrunkGroup_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TrunkGroup;

#ifdef __cplusplus
}
#endif

#endif	/* _TrunkGroup_H_ */
#include <asn_internal.h>
